import type { FitmentDemoPart } from '@/lib/fitment-ai-data'

const VEHICLE_ID = '2014-dodge-durango-limited-36-awd'

export const durangoVehicleNotes = [
  'WD generation Durango (2011-2020) shares its basic architecture with the Jeep Grand Cherokee WK2, so many maintenance and chassis considerations are platform-oriented rather than trim-only.',
  'This explicit record is limited to the 2014 Dodge Durango Limited 3.6L AWD and should not be generalized to the Hemi, SRT, Citadel, RWD, or facelift-specific front-end parts without their own rows.',
  'The 3.6L Pentastar AWD setup is usually a daily/family/towing-light platform first; quietness, brake confidence, cargo utility, and lighting upgrades often matter more than peak-output mods.',
  'Wheel, brake, and lighting choices can vary with factory wheel size, tow package, and lighting package, so notes are kept on individual rows where that matters.',
  'Lowering and larger wheel packages can hurt winter drivability, third-row family ride comfort, and curb-clearance; keep use-case in mind for a three-row SUV.',
  'Roof, hitch, cargo, and interior protection upgrades are especially practical for this platform because owners often mix commuting, road trips, and utility use.',
]

export const durangoParts: FitmentDemoPart[] = [
  {
    id: 'kn-durango-dropin-filter',
    sku: 'KNN-33-2457',
    name: '33-2457 High-Flow Replacement Air Filter',
    brand: 'K&N',
    category: 'intake',
    keywords: ['intake', 'air filter', 'panel filter', 'maintenance', 'daily', 'oem+', 'suv'],
    summary: 'Reusable drop-in panel filter for owners who want a mild intake-side service upgrade without changing the factory airbox layout.',
    priceRange: { min: 64, max: 82 },
    attributes: { install: 'bolt-on', tuneRequired: false, quietFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Grounded as a conservative intake/maintenance-style option for the 3.6L Durango record.' }],
    sourceUrl: 'https://www.knfilters.com/33-2457-replacement-air-filter',
    sourceLabel: 'K&N 33-2457 exact product page',
  },
  {
    id: 'afe-durango-momentum-gt-intake',
    sku: 'AFE-50-70093D',
    name: 'Momentum GT Pro 5R Intake System',
    brand: 'aFe Power',
    category: 'intake',
    keywords: ['intake', 'cold air', 'airbox', 'response', 'sound', 'daily', 'suv'],
    summary: 'Sealed-box style intake option that stays closer to an OEM-style engine-bay presentation than a fully open filter setup.',
    priceRange: { min: 420, max: 500 },
    attributes: { install: 'bolt-on', tuneRequired: false },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use this exact application row only; do not infer fitment to other engines.' }],
    sourceUrl: 'https://afepower.com/',
  },
  {
    id: 'magnaflow-durango-street-series-catback',
    sku: 'MAG-15256',
    name: 'Street Series Cat-Back Exhaust',
    brand: 'MagnaFlow',
    category: 'exhaust',
    keywords: ['exhaust', 'catback', 'street', 'daily', 'tone', 'quiet', 'oem+'],
    summary: 'Street-focused cat-back choice for owners who want more tone than stock without leaning as hard into a loud performance-SUV personality.',
    priceRange: { min: 1140, max: 1300 },
    attributes: { install: 'moderate', loudness: 'medium-low' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Better fit for daily-driver requests than the louder end of the aftermarket.' }],
    sourceUrl: 'https://www.magnaflow.com/',
  },
  {
    id: 'hotchkis-durango-front-rear-sway-bars',
    sku: 'HOT-22836F',
    name: 'Front and Rear Sway Bar Set',
    brand: 'Hotchkis',
    category: 'suspension',
    keywords: ['suspension', 'sway bar', 'handling', 'body roll', 'street', 'family', 'suv'],
    summary: 'One of the more useful family-SUV handling upgrades because it attacks body roll without automatically pushing the vehicle into an ultra-low stance.',
    priceRange: { min: 620, max: 760 },
    attributes: { install: 'moderate', alignmentRequired: false },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Useful for drivers who want flatter cornering while keeping a practical ride height.' }],
    sourceUrl: 'https://www.hotchkis.net/',
  },
  {
    id: 'bilstein-durango-b6-shocks-struts',
    sku: 'BIL-B6-WD36-AWD',
    name: 'B6 Performance Shock and Strut Set',
    brand: 'Bilstein',
    category: 'suspension',
    keywords: ['suspension', 'shock', 'strut', 'daily', 'oem+', 'ride control', 'maintenance', 'suv'],
    summary: 'Damping-focused refresh path for a higher-mileage Durango that needs better body control without committing to a lowered family SUV.',
    priceRange: { min: 760, max: 980 },
    attributes: { install: 'advanced', alignmentRequired: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Grounded here as a practical ride-control and maintenance-adjacent upgrade path.' }],
    sourceUrl: 'https://www.bilstein.com/',
  },
  {
    id: 'ebc-durango-yellowstuff-pads',
    sku: 'EBC-YS-DUR-2014-FR',
    name: 'Yellowstuff Front and Rear Brake Pads',
    brand: 'EBC',
    category: 'brakes',
    keywords: ['brakes', 'pads', 'brake pads', 'pad compound', 'stopping', 'street', 'tow', 'daily', 'suv'],
    summary: 'Performance-street pad option for owners who want more bite than stock, especially on heavier-wheel or utility-used Durangos.',
    priceRange: { min: 240, max: 320 },
    attributes: { install: 'bolt-on', trackBias: false },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Useful where loaded-family, mountain, or light towing use makes stock pads feel soft.' }],
    sourceUrl: 'https://www.ebcbrakes.com/',
  },
  {
    id: 'stoptech-durango-stainless-lines',
    sku: 'STP-950.63015',
    name: 'Stainless Steel Front and Rear Brake Lines',
    brand: 'StopTech',
    category: 'brakes',
    keywords: ['brakes', 'brake lines', 'pedal feel', 'daily', 'tow', 'street'],
    summary: 'Supporting brake upgrade for a firmer pedal feel, especially helpful when combined with better pads and fluid on a heavy AWD SUV.',
    priceRange: { min: 155, max: 220 },
    attributes: { install: 'moderate', brakeFluidBleedRequired: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Supporting hardware rather than a standalone dramatic brake-power change.' }],
    sourceUrl: 'https://www.stoptech.com/',
  },
  {
    id: 'hawk-durango-lts-pads',
    sku: 'HWK-LTS-DUR-2014',
    name: 'LTS Brake Pad Set',
    brand: 'Hawk Performance',
    category: 'brakes',
    keywords: ['brakes', 'pads', 'daily', 'family', 'tow', 'truck suv'],
    summary: 'Truck-and-SUV-oriented pad option that fits the Durango daily/tow/people-hauler use case well.',
    priceRange: { min: 170, max: 230 },
    attributes: { install: 'bolt-on', trackBias: false },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'A grounded brake option for users prioritizing practical SUV use over track language.' }],
    sourceUrl: 'https://www.hawkperformance.com/',
  },
  {
    id: 'voxx-durango-20in-wheel-set',
    sku: 'VOX-20X8-5-5X127-WD',
    name: '20x8.5 Wheel Package',
    brand: 'Voxx',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'rim', 'oem+', 'appearance', 'daily', 'suv'],
    summary: 'Conservative 20-inch wheel-package style entry for owners chasing an OEM+ look rather than an aggressive stance build.',
    priceRange: { min: 1180, max: 1460 },
    attributes: { install: 'bolt-on', finish: 'satin black' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Keep wheel fitment conservative on a family SUV; verify brake clearance and tire load rating before purchase.' }],
    sourceUrl: 'https://www.voxxwheel.com/',
  },
  {
    id: 'michelin-durango-crossclimate2-tire-set',
    sku: 'MIC-CC2-265-50R20',
    name: 'CrossClimate 2 Tire Set',
    brand: 'Michelin',
    category: 'wheels',
    keywords: ['tires', 'all weather', 'daily', 'family', 'road trip', 'winter', 'suv'],
    summary: 'Practical all-weather tire direction for a Durango that sees family duty, wet roads, and mixed-season driving.',
    priceRange: { min: 1040, max: 1360 },
    attributes: { install: 'bolt-on', tireType: 'all-weather' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Tire-size-specific example kept grounded to a common OE-adjacent 20-inch use case; verify actual door-jamb size before ordering.' }],
    sourceUrl: 'https://www.michelinman.com/',
  },
  {
    id: 'weathertech-durango-front-rear-liners',
    sku: 'WT-444421-445422',
    name: 'DigitalFit Floor Liner Set',
    brand: 'WeatherTech',
    category: 'interior',
    keywords: ['interior', 'floor mats', 'liners', 'daily', 'family', 'kids', 'road trip', 'utility'],
    summary: 'One of the most durable real-world Durango upgrades for a three-row family SUV that sees muddy shoes, snacks, and weather.',
    priceRange: { min: 210, max: 285 },
    attributes: { install: 'bolt-on', familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Practical protection-focused interior upgrade rather than a styling part.' }],
    sourceUrl: 'https://www.weathertech.com/dodge/2014/durango/floorliner-digitalfit/',
    sourceLabel: 'WeatherTech 2014 Durango FloorLiner vehicle page',
  },
  {
    id: 'covercraft-durango-sunshade',
    sku: 'CCF-UVS100-DUR14',
    name: 'UVS100 Original Custom Sunscreen',
    brand: 'Covercraft',
    category: 'interior',
    keywords: ['interior', 'sunshade', 'comfort', 'daily', 'road trip', 'family', 'heat'],
    summary: 'Heat-management comfort mod that makes a parked black-interior SUV much easier to live with in daily use.',
    priceRange: { min: 85, max: 110 },
    attributes: { install: 'bolt-on', familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://www.covercraft.com/product/uvs100-custom-sunscreen/UV',
    sourceLabel: 'Covercraft UVS100 exact product page',
  },
  {
    id: 'clazzio-durango-seat-covers',
    sku: 'CLZ-DUR14-LTD-3ROW',
    name: 'Custom Seat Cover Set',
    brand: 'Clazzio',
    category: 'interior',
    keywords: ['interior', 'seat covers', 'family', 'kids', 'oem+', 'daily', 'comfort'],
    summary: 'Interior refresh/protection option that fits the family-SUV brief better than racing-seat style upgrades.',
    priceRange: { min: 520, max: 720 },
    attributes: { install: 'moderate', familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Three-row interior configurations matter; keep to explicit trim/seat-layout applications when shopping.' }],
    sourceUrl: 'https://www.clazzio.com/',
  },
  {
    id: 'kicker-durango-hideaway-hs10',
    sku: 'KIK-51HS10',
    name: 'Hideaway HS10 Powered Subwoofer',
    brand: 'KICKER',
    category: 'audio',
    keywords: ['audio', 'subwoofer', 'sound system', 'interior', 'daily', 'road trip', 'under seat', 'bass'],
    summary: 'Compact powered subwoofer that adds meaningful bass without eating the whole cargo area, which suits a three-row Durango better than a big box build.',
    priceRange: { min: 330, max: 430 },
    attributes: { install: 'moderate', cargoImpact: 'low' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal audio product, but it is a grounded fit-direction for the Durango because packaging is small and installation is custom rather than vehicle-specific.' }],
    sourceUrl: 'https://www.kicker.com/hideaway-hs10',
    sourceLabel: 'KICKER Hideaway HS10 exact product page',
  },
  {
    id: 'infotainment-durango-carplay-kit',
    sku: 'INF-DUR14-UCONNECT-CP',
    name: 'Uconnect CarPlay/Android Auto Upgrade Interface',
    brand: 'Infotainment',
    category: 'audio',
    keywords: ['audio', 'carplay', 'android auto', 'navigation', 'daily', 'family', 'road trip'],
    summary: 'Modern tech-oriented upgrade path for an older family SUV where phone integration often matters more than outright power mods.',
    priceRange: { min: 650, max: 980 },
    attributes: { install: 'advanced', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Radio-screen and factory-option compatibility matter; keep purchase tied to explicit Uconnect application data.' }],
    sourceUrl: 'https://www.infotainment.com/products/2014-2019-dodge-durango-gps-navigation-8-4-4c-nav-uaq-radio-with-apple-carplay-android-auto?variant=39881580847140',
    sourceLabel: 'Infotainment Durango 8.4 CarPlay/Android Auto exact product listing',
  },
  {
    id: 'mopar-durango-hood-deflector',
    sku: 'MOP-82212057',
    name: 'Molded Hood Deflector',
    brand: 'Mopar',
    category: 'appearance',
    keywords: ['appearance', 'exterior', 'oem+', 'hood deflector', 'daily', 'road trip'],
    summary: 'OEM-branded exterior protection/detail piece that fits the subtle-Durango look better than trying to force a track-car aero vibe.',
    priceRange: { min: 120, max: 170 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'mopar-durango-splash-guards',
    sku: 'MOP-82214141AB',
    name: 'Front and Rear Splash Guards',
    brand: 'Mopar',
    category: 'appearance',
    keywords: ['appearance', 'exterior', 'daily', 'winter', 'road trip', 'oem+'],
    summary: 'Practical OEM-style appearance/protection add-on for a daily-driven SUV that sees weather and family use.',
    priceRange: { min: 95, max: 145 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'putco-durango-led-reverse-lights',
    sku: 'PUT-921-LED-DUR',
    name: 'LED Reverse Light Upgrade',
    brand: 'Putco',
    category: 'lighting',
    keywords: ['lighting', 'reverse lights', 'led', 'daily', 'family', 'parking', 'oem+'],
    summary: 'Useful visibility upgrade for reversing a large SUV at night without changing the whole rear lamp assembly.',
    priceRange: { min: 55, max: 95 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Bulb-based upgrade only; verify factory bulb spec before ordering.' }],
    sourceUrl: 'https://www.putco.com/',
  },
  {
    id: 'mopar-durango-roof-rack-crossbars',
    sku: 'MOP-82214552',
    name: 'Roof Rack Crossbar Kit',
    brand: 'Mopar',
    category: 'utility',
    keywords: ['utility', 'roof rack', 'cargo', 'road trip', 'family', 'outdoors', 'crossbars', 'extra storage', 'haul gear'],
    summary: 'One of the most grounded utility upgrades for expanding luggage capacity on a three-row road-trip vehicle.',
    priceRange: { min: 250, max: 340 },
    attributes: { install: 'bolt-on', familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Requires compatible roof side rails; keep purchase tied to the actual roof configuration.' }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'thule-durango-cargo-box',
    sku: 'THU-MOTION3-L',
    name: 'Motion 3 L Cargo Box',
    brand: 'Thule',
    category: 'utility',
    keywords: ['utility', 'cargo box', 'roof rack', 'road trip', 'family', 'storage', 'roof box', 'carry luggage', 'extra storage'],
    summary: 'Cargo-box style add-on for family travel once crossbars are in place, especially valuable when the third row is occupied.',
    priceRange: { min: 900, max: 1100 },
    attributes: { install: 'bolt-on', requiresCrossbars: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal cargo box, so fitment depends on installed crossbars and clearance rather than a naked-roof vehicle claim.' }],
    sourceUrl: 'https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-motion-3-l-_-639750',
    sourceLabel: 'Thule Motion 3 L exact product page',
  },
  {
    id: 'mopar-durango-trailer-hitch',
    sku: 'MOP-82213951',
    name: 'Trailer Hitch Receiver Kit',
    brand: 'Mopar',
    category: 'utility',
    keywords: ['utility', 'tow', 'towing', 'hitch', 'cargo carrier', 'bike rack'],
    summary: 'Grounded utility hardware for towing light loads or carrying hitch-mounted cargo and bike racks.',
    priceRange: { min: 420, max: 560 },
    attributes: { install: 'advanced', towFocused: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Receiver fitment is explicit here, but actual tow rating still depends on cooling, gearing, and factory tow-package equipment.' }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'tekonsha-durango-brake-controller',
    sku: 'TEK-90195',
    name: 'Prodigy P3 Trailer Brake Controller',
    brand: 'Tekonsha',
    category: 'utility',
    keywords: ['utility', 'tow', 'towing', 'brake controller', 'trailer'],
    summary: 'Useful towing-support hardware for owners pulling a trailer with electric brakes rather than just adding a hitch for accessories.',
    priceRange: { min: 165, max: 220 },
    attributes: { install: 'moderate', towFocused: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal brake controller; the grounded part is the exact controller itself, while the Durango still needs the right bracket, wiring, and tow readiness.' }],
    sourceUrl: 'https://www.tekonsha.com/product/90195_trailer-brake-control-proportional',
    sourceLabel: 'Tekonsha Prodigy P3 exact product page',
  },
  {
    id: 'weathertech-durango-cargo-liner',
    sku: 'WT-401032',
    name: 'Cargo Liner',
    brand: 'WeatherTech',
    category: 'utility',
    keywords: ['utility', 'cargo', 'liner', 'family', 'pets', 'road trip', 'daily'],
    summary: 'Cargo-area protection that is especially useful when the Durango alternates between stroller/dog/gear duty and nicer family hauling.',
    priceRange: { min: 135, max: 185 },
    attributes: { install: 'bolt-on', familyFriendly: true },
    resultType: 'accessory',
    intentTags: ['utility', 'comfort'],
    exactMatchPhrases: ['cargo liner', 'cargo mat', 'trunk liner'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Cargo-area shape varies with third-row position; use explicit row/seat-position application data when buying.' }],
    sourceUrl: 'https://www.weathertech.com/dodge/2014/durango/cargo-liner/',
    sourceLabel: 'WeatherTech 2014 Durango Cargo Liner vehicle page',
  },
  {
    id: 'mopar-durango-all-weather-cargo-tray',
    sku: 'MOP-82214519',
    name: 'All-Weather Cargo Tray',
    brand: 'Mopar',
    category: 'utility',
    keywords: ['utility', 'cargo tray', 'oem+', 'daily', 'family'],
    summary: 'OEM-style cargo protection option for owners who want a subtler utility add-on than a tall deep cargo liner.',
    priceRange: { min: 95, max: 140 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'mopar-durango-engine-air-filter-service',
    sku: 'MOP-ENGINE-AIR-SVC',
    name: 'OEM-Style Engine Air Filter Service Item',
    brand: 'Mopar',
    category: 'maintenance',
    keywords: ['maintenance', 'service', 'air filter', 'daily', 'oem+', 'practical'],
    summary: 'Explicit maintenance-style record so search can answer practical service-oriented requests without inventing performance hardware.',
    priceRange: { min: 22, max: 36 },
    attributes: { install: 'bolt-on', serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'mopar-durango-cabin-air-filter-service',
    sku: 'MOP-CABIN-FILTER-SVC',
    name: 'OEM-Style Cabin Air Filter Service Item',
    brand: 'Mopar',
    category: 'maintenance',
    keywords: ['maintenance', 'service', 'cabin filter', 'comfort', 'daily', 'family'],
    summary: 'Useful practical row for comfort-oriented searches because cabin-air service is a real quality-of-life upgrade in an older family SUV.',
    priceRange: { min: 18, max: 30 },
    attributes: { install: 'bolt-on', serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'mopar-durango-wiper-blade-kit',
    sku: 'MOP-WIPER-KIT-DUR14',
    name: 'Wiper Blade Service Kit',
    brand: 'Mopar',
    category: 'maintenance',
    keywords: ['maintenance', 'wipers', 'visibility', 'daily', 'winter', 'practical'],
    summary: 'Another intentionally grounded service item so practical ownership requests return something useful instead of hallucinated upgrades.',
    priceRange: { min: 34, max: 58 },
    attributes: { install: 'bolt-on', serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'lasfit-durango-led-interior-kit',
    sku: 'LSF-DUR14-INTLED',
    name: 'LED Interior Light Kit',
    brand: 'LASFIT',
    category: 'lighting',
    keywords: ['lighting', 'interior lights', 'led', 'family', 'daily', 'oem+', 'ambient lighting'],
    summary: 'Low-drama interior lighting refresh that makes a used family SUV feel newer and more usable at night.',
    priceRange: { min: 45, max: 75 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Bulb-content kits can vary by interior package; verify exact bulb map before purchase.' }],
    sourceUrl: 'https://www.lasfit.com/',
    sourceLabel: 'LASFIT brand page (broad; exact live Durango kit page not confidently verified)',
  },

  {
    id: 'durango-headliner-parts-lookup',
    sku: 'DUR14-HDLNR-LOOKUP',
    name: 'Headliner / Pillar Trim Parts Lookup',
    brand: 'Mopar',
    category: 'interior',
    keywords: ['interior', 'headliner', 'roof liner', 'pillar trim', 'interior styling'],
    summary: 'Honest lookup-style row for headliner questions, because exact live Durango headliner conversion kits were not confidently verified during this pass.',
    priceRange: { min: 250, max: 1200 },
    attributes: { install: 'advanced', oemStyle: true },
    resultType: 'parts-lookup',
    intentTags: ['replacement', 'cosmetic'],
    styleTags: ['factory-like'],
    exactMatchPhrases: ['headliner replacement', 'roof liner replacement', 'headliner parts'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Kept intentionally honest: treat this as a parts-lookup direction, not a verified all-in-one conversion kit.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20headliner',
    sourceLabel: 'Mopar headliner parts search (broad by necessity)',
  },
  {
    id: 'durango-steering-wheel-parts-lookup',
    sku: 'DUR14-SW-LOOKUP',
    name: 'Steering Wheel Parts Lookup',
    brand: 'Mopar',
    category: 'interior',
    keywords: ['interior', 'steering wheel', 'replacement steering wheel', 'oem steering wheel', 'factory wheel'],
    summary: 'Honest steering-wheel lookup row so true steering-wheel searches do not collapse into covers or wraps when an exact live replacement-wheel page is not confidently verified.',
    priceRange: { min: 420, max: 980 },
    attributes: { install: 'advanced', oemStyle: true },
    resultType: 'parts-lookup',
    intentTags: ['replacement'],
    styleTags: ['factory-like', 'oem-like'],
    exactMatchPhrases: ['steering wheel replacement', 'oem steering wheel', 'factory steering wheel'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use VIN-backed lookup before purchase because wheel controls, heat, trim, and airbag-related details vary.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20steering%20wheel',
    sourceLabel: 'Mopar steering-wheel parts search (broad by necessity)',
  },
  {
    id: 'durango-steering-wheel-trim-lookup',
    sku: 'DUR14-SW-TRIM-LOOKUP',
    name: 'Steering Wheel Trim / Bezel Parts Lookup',
    brand: 'Mopar',
    category: 'interior',
    keywords: ['interior', 'steering wheel trim', 'steering wheel bezel', 'steering wheel accent', 'trim bezel'],
    summary: 'Honest trim/bezel lookup row for steering-wheel-trim questions when an exact live Durango trim listing was not confidently verified.',
    priceRange: { min: 55, max: 220 },
    attributes: { install: 'moderate', oemStyle: true },
    resultType: 'parts-lookup',
    intentTags: ['replacement', 'cosmetic'],
    styleTags: ['factory-like', 'subtle'],
    exactMatchPhrases: ['steering wheel trim', 'steering wheel bezel', 'wheel bezel'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Switch openings and finish details vary with wheel style, so keep this as a lookup direction rather than a claimed exact trim kit.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20steering%20wheel%20bezel',
    sourceLabel: 'Mopar steering-wheel trim search (broad by necessity)',
  },
  {
    id: 'wheelskins-durango-steering-wheel-wrap',
    sku: 'WSK-DUR14-SW',
    name: 'Custom Leather Steering Wheel Cover',
    brand: 'Wheelskins',
    category: 'interior',
    keywords: ['interior', 'steering wheel cover', 'steering wheel wrap', 'wheel wrap', 'steering wheel cover', 'comfort', 'daily', 'oem+'],
    summary: 'Exact-fit leather wrap option for drivers who want the steering wheel to feel newer without swapping in a different wheel core.',
    priceRange: { min: 95, max: 145 },
    attributes: { install: 'moderate', oemStyle: true },
    resultType: 'accessory',
    intentTags: ['comfort', 'cosmetic'],
    styleTags: ['premium', 'oem-like'],
    exactMatchPhrases: ['steering wheel cover', 'steering wheel wrap', 'wheel wrap'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Keep to the correct factory wheel shape and spoke layout when ordering.' }],
    sourceUrl: 'https://wheelskins.com/original',
    sourceLabel: 'Wheelskins Original steering wheel cover page',
  },
  {
    id: 'redlinegoods-durango-steering-wheel-rewrap-kit',
    sku: 'RLG-DUR14-SW-REWRAP',
    name: 'Custom Steering Wheel Rewrap Kit',
    brand: 'RedlineGoods',
    category: 'interior',
    keywords: ['interior', 'steering wheel cover', 'steering wheel wrap', 'wheel rewrap', 'suede', 'leather', 'oem+'],
    summary: 'More upgrade-oriented steering-wheel rewrap direction for owners who want a nicer material and stitched finish rather than a loose slip-on cover.',
    priceRange: { min: 120, max: 220 },
    attributes: { install: 'advanced', oemStyle: true },
    resultType: 'accessory',
    intentTags: ['cosmetic', 'comfort'],
    styleTags: ['premium', 'suede', 'sporty'],
    exactMatchPhrases: ['steering wheel rewrap', 'custom steering wheel wrap', 'alcantara steering wheel wrap'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Best treated as a rewrap/upholstery path, not a replacement wheel core.' }],
    sourceUrl: 'https://www.redlinegoods.com/',
    sourceLabel: 'RedlineGoods steering wheel rewrap family page',
  },
  {
    id: 'durango-interior-trim-kit-lookup',
    sku: 'DUR14-TRIMKIT-LOOKUP',
    name: 'Interior Trim Kit / Dash Trim Lookup',
    brand: 'Mopar / aftermarket mixed',
    category: 'interior',
    keywords: ['interior', 'trim kit', 'interior trim', 'dash trim', 'wood trim', 'carbon trim', 'interior styling'],
    summary: 'Specific trim-kit lookup row so interior styling searches can land on trim-focused answers instead of broad comfort or utility items.',
    priceRange: { min: 80, max: 420 },
    attributes: { install: 'moderate', oemStyle: true },
    resultType: 'parts-lookup',
    intentTags: ['cosmetic'],
    styleTags: ['subtle', 'carbon-look', 'wood-look'],
    exactMatchPhrases: ['interior trim kit', 'dash trim kit', 'carbon trim kit'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Finish, piece count, and trim-level coverage vary too much to pretend one exact universal kit was verified.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20interior%20trim',
    sourceLabel: 'Mopar/interior trim search (broad by necessity)',
  },
  {
    id: 'durango-suede-headliner-upholstery-lookup',
    sku: 'DUR14-SUEDE-HDLNR-LOOKUP',
    name: 'Suede Headliner Upholstery Direction',
    brand: 'Local upholstery / material path',
    category: 'interior',
    keywords: ['interior', 'suede headliner', 'alcantara headliner', 'microsuede headliner', 'headliner upholstery'],
    summary: 'Honest upholstery-style direction for people asking for a suede or Alcantara-like headliner, because that request is usually a trim/upholstery job rather than a one-click Durango kit.',
    priceRange: { min: 450, max: 1600 },
    attributes: { install: 'advanced', oemStyle: false },
    resultType: 'parts-lookup',
    intentTags: ['cosmetic'],
    styleTags: ['premium', 'suede'],
    exactMatchPhrases: ['suede headliner', 'alcantara headliner', 'microsuede headliner'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Kept deliberately honest: this is an upholstery/material path, not a verified pre-made Durango-specific suede kit.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20headliner',
    sourceLabel: 'Durango headliner lookup baseline (use upholstery judgment)',
  },
  {
    id: 'durango-steering-wheel-carbon-trim-lookup',
    sku: 'DUR14-SW-CARBON-TRIM',
    name: 'Steering Wheel Accent Trim Lookup',
    brand: 'Aftermarket trim / overlay mixed',
    category: 'interior',
    keywords: ['interior', 'steering wheel trim', 'steering wheel accent', 'carbon steering trim', 'wheel bezel'],
    summary: 'More styling-oriented steering-wheel-trim row so trim searches do not collapse into wheel replacement or generic interior accessories.',
    priceRange: { min: 35, max: 180 },
    attributes: { install: 'bolt-on', oemStyle: false },
    resultType: 'accessory',
    intentTags: ['cosmetic'],
    styleTags: ['carbon-look', 'sporty'],
    exactMatchPhrases: ['steering wheel trim', 'steering wheel accent trim', 'carbon steering wheel trim'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Treat as trim-overlay/bezels direction rather than a full wheel assembly.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20steering%20wheel%20trim',
    sourceLabel: 'Steering-wheel trim lookup (broad by necessity)',
  },
  {
    id: 'govee-durango-ambient-light-bars',
    sku: 'GV-INT-RGBIC-BARS',
    name: 'Aftermarket Interior Ambient Light Bar Kit',
    brand: 'Govee',
    category: 'interior',
    keywords: ['interior', 'ambient lighting', 'ambient light', 'footwell lights', 'appearance', 'tech', 'rgb'],
    summary: 'Honest aftermarket ambient-lighting direction for owners who want cabin glow and color accents, without pretending it is a factory-style Durango-specific kit.',
    priceRange: { min: 45, max: 90 },
    attributes: { install: 'moderate', oemStyle: false },
    resultType: 'universal',
    intentTags: ['cosmetic', 'tech'],
    styleTags: ['rgb', 'sporty'],
    exactMatchPhrases: ['ambient lighting', 'footwell lights', 'interior ambient lighting'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal interior-lighting product category rather than a Durango-specific molded kit; routing, power pickoff, and finish quality depend on the install.' }],
    sourceUrl: 'https://us.govee.com/',
    sourceLabel: 'Govee product family / brand page (broad by necessity)',
  },
  {
    id: 'infotainment-durango-oem-radio-upgrade',
    sku: 'INF-DUR14-84NAV',
    name: 'Factory-Style 8.4 Radio Upgrade Package',
    brand: 'Infotainment',
    category: 'audio',
    keywords: ['audio', 'uconnect', 'radio upgrade', 'carplay', 'android auto', 'tech', 'oem+'],
    summary: 'More specific radio-upgrade path for Durango owners who ask for a nicer screen or newer factory-style tech experience.',
    priceRange: { min: 1295, max: 1795 },
    attributes: { install: 'advanced', oemStyle: true },
    resultType: 'aftermarket-upgrade',
    intentTags: ['tech'],
    styleTags: ['factory-like', 'premium'],
    exactMatchPhrases: ['radio upgrade', 'uconnect upgrade', 'factory-style radio upgrade'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Screen size, HVAC stack, and donor-module compatibility matter; keep to explicit 2014 Durango conversion listings.' }],
    sourceUrl: 'https://www.infotainment.com/products/2014-2019-dodge-durango-gps-navigation-8-4-4c-nav-uaq-radio-with-apple-carplay-android-auto?variant=39881580847140',
    sourceLabel: 'Infotainment Durango 8.4 radio exact product listing',
  },
  {
    id: 'kicker-durango-front-door-speakers',
    sku: 'KIK-51KSC6504',
    name: 'KS Series 6.5" Coax Speakers',
    brand: 'KICKER',
    category: 'audio',
    keywords: ['audio', 'speakers', 'speaker upgrade', 'door speakers', 'daily', 'road trip', 'clarity'],
    summary: 'Aftermarket speaker direction for owners asking for cleaner, louder daily audio without jumping straight to a full custom build.',
    priceRange: { min: 95, max: 140 },
    attributes: { install: 'moderate', cargoImpact: 'none' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal speaker product, but it is a grounded Durango upgrade path because the exact speaker page is live; verify door depth, impedance, and factory-amplifier integration before purchase.' }],
    sourceUrl: 'https://www.kicker.com/51KSC6504',
    sourceLabel: 'KICKER KS 6.5-inch coax exact product page',
  },
  {
    id: 'kicker-durango-dash-speakers',
    sku: 'KIK-51KSC3504',
    name: 'KS Series 3.5" Dash Speakers',
    brand: 'KICKER',
    category: 'audio',
    keywords: ['audio', 'speakers', 'dash speakers', 'speaker upgrade', 'daily', 'clarity', 'front stage'],
    summary: 'Specific small-speaker option for owners trying to improve front-stage clarity instead of only adding bass.',
    priceRange: { min: 85, max: 120 },
    attributes: { install: 'moderate', cargoImpact: 'none' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Grounded as an exact live speaker product that commonly fits dash-speaker upgrade conversations, but actual Durango mount depth and connector details still need verification at install time.' }],
    sourceUrl: 'https://www.kicker.com/51KSC3504',
    sourceLabel: 'KICKER KS 3.5-inch coax exact product page',
  },
  {
    id: 'morimoto-durango-xb-headlights',
    sku: 'MRM-DUR14-XBHL',
    name: 'XB LED Headlight Assembly Set',
    brand: 'Morimoto',
    category: 'lighting',
    keywords: ['lighting', 'headlights', 'headlight', 'projector headlights', 'led', 'appearance'],
    summary: 'Specific headlight-assembly result so headlight searches do not fall back to unrelated fog or reverse-light items.',
    priceRange: { min: 1380, max: 1650 },
    attributes: { install: 'advanced', oemStyle: true },
    resultType: 'aftermarket-upgrade',
    intentTags: ['aftermarket-upgrade', 'cosmetic'],
    exactMatchPhrases: ['headlight assembly', 'led headlights', 'projector headlights'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Front-end and factory-lighting-package differences matter; keep to explicit 2014 Durango rows only.' }],
    sourceUrl: 'https://www.morimotohid.com/morimoto-14-15-dodge-durango-xb-led-headlights',
    sourceLabel: 'Morimoto XB LED headlights exact product page',
  },
  {
    id: 'vland-durango-led-tail-lights',
    sku: 'VLD-DUR14-TL',
    name: 'LED Tail Light Assembly Set',
    brand: 'VLAND',
    category: 'lighting',
    keywords: ['lighting', 'tail lights', 'tail lamp', 'rear lights', 'led', 'appearance'],
    summary: 'Specific rear-light result for tail-light searches instead of broad lighting filler.',
    priceRange: { min: 420, max: 560 },
    attributes: { install: 'bolt-on', oemStyle: false },
    resultType: 'aftermarket-upgrade',
    intentTags: ['aftermarket-upgrade', 'cosmetic'],
    exactMatchPhrases: ['tail light assembly', 'led tail lights', 'tail lamp assembly'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Tail-lamp connector and facelift differences matter; keep to explicit 2014-compatible assemblies.' }],
    sourceUrl: 'https://www.vland-official.com/',
    sourceLabel: 'VLAND brand page (broad; exact live Durango tail-light page not confidently verified)',
  },
  {
    id: 'precisionled-durango-puddle-lights',
    sku: 'PL-DUR14-PDL',
    name: 'LED Puddle Light Kit',
    brand: 'PrecisionLED',
    category: 'lighting',
    keywords: ['lighting', 'puddle lights', 'door lights', 'led', 'appearance', 'oem+'],
    summary: 'Small but specific lighting result for people asking about puddle or door lights.',
    priceRange: { min: 24, max: 42 },
    attributes: { install: 'bolt-on', oemStyle: true },
    resultType: 'accessory',
    intentTags: ['cosmetic'],
    exactMatchPhrases: ['puddle lights', 'door lights'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Mirror or door-lamp bulb style should stay tied to the explicit Durango kit.' }],
    sourceUrl: 'https://precisionled.com/',
    sourceLabel: 'PrecisionLED brand page (broad; exact live Durango puddle-light page not confidently verified)',
  },
  {
    id: 'diode-durango-license-plate-lights',
    sku: 'DD-DUR14-LPL',
    name: 'LED License Plate Light Pair',
    brand: 'Diode Dynamics',
    category: 'lighting',
    keywords: ['lighting', 'license plate lights', 'tag lights', 'led', 'oem+', 'appearance'],
    summary: 'Exact small-lighting row for owners asking for plate or tag lights instead of generic lighting results.',
    priceRange: { min: 28, max: 48 },
    attributes: { install: 'bolt-on', oemStyle: true },
    resultType: 'accessory',
    intentTags: ['cosmetic'],
    exactMatchPhrases: ['license plate lights', 'tag lights'],
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://www.diodedynamics.com/',
    sourceLabel: 'Diode Dynamics brand page (broad; exact live Durango plate-light page not confidently verified)',
  },
  {
    id: 'stoptech-durango-slotted-rotor-kit',
    sku: 'STP-DUR14-SPORT-ROT',
    name: 'Sport Slotted Rotor Kit',
    brand: 'StopTech',
    category: 'brakes',
    keywords: ['brakes', 'rotors', 'brake rotors', 'stopping', 'street', 'tow'],
    summary: 'Rotor-specific answer for owners explicitly asking about rotors or warped-stock-rotor replacements.',
    priceRange: { min: 295, max: 410 },
    attributes: { install: 'moderate', trackBias: false },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Rotor dimensions vary with brake package and wheel size; keep to exact Durango application rows.' }],
    sourceUrl: 'https://www.stoptech.com/',
  },
  {
    id: 'mopar-durango-cargo-net',
    sku: 'MOP-82214047',
    name: 'Rear Cargo Net',
    brand: 'Mopar',
    category: 'utility',
    keywords: ['utility', 'cargo net', 'storage net', 'daily', 'family', 'practical'],
    summary: 'Low-cost specific cargo-management result for owners who ask for a net instead of a liner or roof-storage setup.',
    priceRange: { min: 48, max: 74 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'trex-durango-upper-grille',
    sku: 'TRX-DUR14-GRILLE',
    name: 'Upper Mesh Grille Kit',
    brand: 'T-Rex Grilles',
    category: 'appearance',
    keywords: ['appearance', 'grille', 'front grille', 'exterior', 'aggressive', 'style'],
    summary: 'Specific front-grille result for exterior-style searches that really mean grille, not any appearance item.',
    priceRange: { min: 420, max: 610 },
    attributes: { install: 'moderate', oemStyle: false },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Front fascia differences matter across years and trims; keep to explicit 2014 Durango applications.' }],
    sourceUrl: 'https://trexbillet.com/',
  },
  {
    id: 'mopar-durango-mirror-caps',
    sku: 'MOP-DUR14-MCAP',
    name: 'Body-Color Mirror Cap Set',
    brand: 'Mopar',
    category: 'appearance',
    keywords: ['appearance', 'mirror caps', 'mirror covers', 'oem+', 'subtle', 'exterior'],
    summary: 'Small OEM-style appearance detail for people asking about mirror caps or a subtler exterior cleanup.',
    priceRange: { min: 88, max: 138 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Mirror-signal and finish differences matter, so stay tied to explicit Durango cap variants.' }],
    sourceUrl: 'https://store.mopar.com/',
  },
  {
    id: 'afe-durango-magnum-flow-pro-dry-filter',
    sku: 'AFE-31-10226',
    name: 'Magnum FLOW Pro DRY S Replacement Filter',
    brand: 'aFe Power',
    category: 'intake',
    keywords: ['intake', 'air filter', 'dry filter', 'panel filter', 'maintenance', 'response', 'daily'],
    summary: 'Dry reusable filter option for owners who want a mild intake refresh without stepping up to a full intake system.',
    priceRange: { min: 72, max: 96 },
    attributes: { install: 'bolt-on', tuneRequired: false, quietFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Kept as a conservative filter-only intake row for the exact Durango record.' }],
    sourceUrl: 'https://afepower.com/afe-power-31-10226-magnum-flow-pro-dry-s-air-filter',
    sourceLabel: 'aFe Power exact product page',
  },
  {
    id: 'borla-durango-touring-catback',
    sku: 'BOR-140625',
    name: 'Touring Cat-Back Exhaust',
    brand: 'Borla',
    category: 'exhaust',
    keywords: ['exhaust', 'catback', 'touring', 'quiet', 'daily', 'oem+', 'tone'],
    summary: 'Quieter Borla direction for owners who want a nicer tone but do not want the Durango to feel loud or tiring on family trips.',
    priceRange: { min: 1320, max: 1490 },
    attributes: { install: 'moderate', loudness: 'medium-low' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use exact 3.6L application data only; this row is intended for quieter exhaust searches.' }],
    sourceUrl: 'https://www.borla.com/products/dodge-durango-cat-back-exhaust-system-140625',
    sourceLabel: 'Borla exact Touring cat-back product page',
  },
  {
    id: 'moog-durango-front-sway-bar-links',
    sku: 'MOG-K750809-K750810',
    name: 'Front Sway Bar Link Pair',
    brand: 'MOOG',
    category: 'suspension',
    keywords: ['suspension', 'sway bar links', 'front end', 'refresh', 'maintenance', 'handling', 'clunk'],
    summary: 'Practical front-end refresh item for Durangos with worn links, clunks, or lazy roll-control feel.',
    priceRange: { min: 58, max: 96 },
    attributes: { install: 'moderate', alignmentRequired: false, serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Service-style suspension row for worn original hardware rather than a dramatic performance mod.' }],
    sourceUrl: 'https://www.moogparts.com/',
    sourceLabel: 'MOOG catalog / family page (application should stay VIN/vehicle checked)',
  },
  {
    id: 'monroe-durango-quick-strut-front',
    sku: 'MON-172285-172286',
    name: 'Quick-Strut Front Assembly Pair',
    brand: 'Monroe',
    category: 'suspension',
    keywords: ['suspension', 'struts', 'front struts', 'ride comfort', 'refresh', 'maintenance', 'daily'],
    summary: 'Front complete-strut refresh path for older Durangos where restoring ride quality matters more than lowering it.',
    priceRange: { min: 330, max: 460 },
    attributes: { install: 'advanced', alignmentRequired: true, serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Treat as a comfort-refresh option; confirm AWD-specific front application before purchase.' }],
    sourceUrl: 'https://www.monroe.com/',
    sourceLabel: 'Monroe family/catalog page (application should stay vehicle checked)',
  },
  {
    id: 'bilstein-durango-b6-front-struts',
    sku: 'BIL-35-197631-35-197648',
    name: 'B6 Front Strut Pair',
    brand: 'Bilstein',
    category: 'suspension',
    keywords: ['suspension', 'front struts', 'ride control', 'handling', 'comfort refresh', 'oem+', 'daily'],
    summary: 'More explicit front-only Bilstein row for owners refreshing the nose of a higher-mileage AWD Durango.',
    priceRange: { min: 290, max: 390 },
    attributes: { install: 'advanced', alignmentRequired: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Verify exact front left/right AWD application before ordering; kept separate from the full set row.' }],
    sourceUrl: 'https://www.bilstein.com/us/en/',
    sourceLabel: 'Bilstein family page (broad; exact live Durango application page not confidently verified)',
  },
  {
    id: 'bilstein-durango-b6-rear-shocks',
    sku: 'BIL-24-197649',
    name: 'B6 Rear Shock Pair',
    brand: 'Bilstein',
    category: 'suspension',
    keywords: ['suspension', 'rear shocks', 'ride control', 'comfort refresh', 'handling', 'daily', 'family'],
    summary: 'Rear damping refresh for Durangos that feel floaty or under-controlled with passengers and cargo aboard.',
    priceRange: { min: 220, max: 320 },
    attributes: { install: 'moderate', alignmentRequired: false },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Useful for comfort/control refresh queries where a full lowering setup is the wrong answer.' }],
    sourceUrl: 'https://www.bilstein.com/us/en/',
    sourceLabel: 'Bilstein family page (broad; exact live Durango rear-shock page not confidently verified)',
  },
  {
    id: 'powerstop-durango-z36-truck-tow-kit',
    sku: 'PWR-K7003-36',
    name: 'Z36 Truck & Tow Brake Kit',
    brand: 'PowerStop',
    category: 'brakes',
    keywords: ['brakes', 'pads', 'rotors', 'truck and tow', 'towing', 'mountains', 'family', 'suv'],
    summary: 'Tow-and-load-friendly brake package for owners who haul people, luggage, mountain grades, or occasional trailers.',
    priceRange: { min: 340, max: 440 },
    attributes: { install: 'moderate', trackBias: false, towFocused: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Grounded as the more towing-biased PowerStop direction for the exact Durango record.' }],
    sourceUrl: 'https://www.powerstop.com/product/power-stop-z36-brake-kit/',
    sourceLabel: 'PowerStop Z36 brake kit family page',
  },
  {
    id: 'powerstop-durango-z23-front-pads',
    sku: 'PWR-16-1057',
    name: 'Z23 Front Brake Pad Set',
    brand: 'PowerStop',
    category: 'brakes',
    keywords: ['brakes', 'front pads', 'brake pads', 'daily', 'street', 'family', 'suv'],
    summary: 'Budget-friendlier front pad-only answer for owners who need a grounded daily-driver brake refresh.',
    priceRange: { min: 52, max: 78 },
    attributes: { install: 'bolt-on', trackBias: false },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Pad-only service row so the tool can answer front-brake-refresh questions more precisely.' }],
    sourceUrl: 'https://www.powerstop.com/',
    sourceLabel: 'PowerStop catalog / family page (application should stay vehicle checked)',
  },
  {
    id: 'centric-durango-premium-rotor-set',
    sku: 'CNT-DUR14-PREM-ROT',
    name: 'Premium Plain Rotor Set',
    brand: 'Centric',
    category: 'brakes',
    keywords: ['brakes', 'rotors', 'plain rotors', 'maintenance', 'daily', 'oem+', 'service'],
    summary: 'Straightforward rotor-refresh direction for owners who want quality stock-style replacement rather than drilled/slotted styling.',
    priceRange: { min: 180, max: 290 },
    attributes: { install: 'moderate', trackBias: false, serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Rotor dimensions vary by axle and package, so keep the actual purchase tied to exact Durango application data.' }],
    sourceUrl: 'https://centricparts.com/',
    sourceLabel: 'Centric family/catalog page (broad by necessity)',
  },
  {
    id: 'motul-dot4-brake-fluid',
    sku: 'MTL-RBF600',
    name: 'RBF 600 DOT 4 Brake Fluid',
    brand: 'Motul',
    category: 'brakes',
    keywords: ['brakes', 'brake fluid', 'dot 4', 'pedal feel', 'mountains', 'service', 'tow'],
    summary: 'Brake-fluid service direction for Durangos that work hard in mountain driving, loaded trips, or towing-light use.',
    priceRange: { min: 24, max: 42 },
    attributes: { install: 'moderate', brakeFluidBleedRequired: true, serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal fluid product, but a grounded supporting row for real-world brake-service conversations on a heavy SUV.' }],
    sourceUrl: 'https://www.motul.com/us/en-US/products/rbf-600-factory-line',
    sourceLabel: 'Motul RBF 600 exact product page',
  },
  {
    id: 'continental-durango-crosscontact-lx25-set',
    sku: 'CON-LX25-265-50R20',
    name: 'CrossContact LX25 Tire Set',
    brand: 'Continental',
    category: 'wheels',
    keywords: ['tires', 'touring tire', 'all season', 'daily', 'comfort', 'road trip', 'suv'],
    summary: 'Comfort-biased touring tire direction for Durango owners prioritizing highway manners and family-road-trip use.',
    priceRange: { min: 980, max: 1280 },
    attributes: { install: 'bolt-on', tireType: 'all-season' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Kept grounded to a common OE-adjacent 20-inch direction; verify the door-jamb tire size on the actual SUV.' }],
    sourceUrl: 'https://continentaltire.com/tires/crosscontact-lx25',
    sourceLabel: 'Continental CrossContact LX25 exact product family page',
  },
  {
    id: 'falken-durango-wildpeak-at-trail-set',
    sku: 'FLK-ATTRAIL-265-50R20',
    name: 'Wildpeak A/T Trail Tire Set',
    brand: 'Falken',
    category: 'wheels',
    keywords: ['tires', 'all terrain', 'winter', 'trail', 'appearance', 'suv', 'road trip'],
    summary: 'More rugged tire direction for owners chasing a subtle adventure look without turning the Durango into a fake rock crawler.',
    priceRange: { min: 1040, max: 1360 },
    attributes: { install: 'bolt-on', tireType: 'all-terrain' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Grounded as a tire-direction row only; exact usable size depends on the actual wheel/tire package.' }],
    sourceUrl: 'https://www.falkentire.com/wildpeak/attrail',
    sourceLabel: 'Falken Wildpeak A/T Trail exact product family page',
  },
  {
    id: 'mopar-durango-oem-wheel-lookup',
    sku: 'MOP-DUR14-WHEEL-LOOKUP',
    name: 'Factory Wheel / Wheel Package Lookup',
    brand: 'Mopar',
    category: 'wheels',
    keywords: ['wheels', 'factory wheels', 'oem wheels', 'wheel replacement', 'stock rims', 'oem+'],
    summary: 'Honest lookup-style row for owners asking about stock-style replacement wheels or OEM+ take-off direction.',
    priceRange: { min: 260, max: 760 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use VIN-backed wheel lookup because factory size and finish can vary with package and original equipment.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20wheel',
    sourceLabel: 'Mopar wheel search (broad by necessity)',
  },
  {
    id: 'lasfit-durango-exterior-led-bulb-lookup',
    sku: 'LSF-DUR14-EXTLED',
    name: 'Exterior LED Bulb Upgrade Lookup',
    brand: 'LASFIT',
    category: 'lighting',
    keywords: ['lighting', 'led bulbs', 'headlight bulbs', 'fog bulbs', 'reverse bulbs', 'license lights', 'brighter'],
    summary: 'Honest bulb-upgrade direction for owners asking about swapping multiple exterior bulbs to LED without claiming one exact all-inclusive kit page.',
    priceRange: { min: 25, max: 180 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Bulb types vary by factory lighting package, so keep this as a vehicle-lookup direction rather than a one-click exact kit claim.' }],
    sourceUrl: 'https://www.lasfit.com/pages/vehicle-finder',
    sourceLabel: 'LASFIT vehicle finder / bulb lookup',
  },
  {
    id: 'mopar-durango-headlight-parts-lookup',
    sku: 'MOP-DUR14-HL-LOOKUP',
    name: 'Factory Headlight / Headlamp Parts Lookup',
    brand: 'Mopar',
    category: 'lighting',
    keywords: ['lighting', 'headlights', 'headlamp', 'oem headlights', 'factory headlight', 'replacement headlight'],
    summary: 'Honest OEM headlight lookup row for people who want stock-style replacement rather than aftermarket projector styling.',
    priceRange: { min: 180, max: 980 },
    attributes: { install: 'advanced', oemStyle: true },
    resultType: 'parts-lookup',
    intentTags: ['replacement'],
    styleTags: ['factory-like', 'oem-like'],
    exactMatchPhrases: ['oem headlights', 'factory headlight', 'replacement headlight'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Halogen/HID package differences matter, so this stays a VIN-backed Mopar lookup direction.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20headlamp',
    sourceLabel: 'Mopar headlight search (broad by necessity)',
  },
  {
    id: 'mopar-durango-tail-light-parts-lookup',
    sku: 'MOP-DUR14-TL-LOOKUP',
    name: 'Factory Tail Light / Tail Lamp Parts Lookup',
    brand: 'Mopar',
    category: 'lighting',
    keywords: ['lighting', 'tail lights', 'tail lamp', 'rear lamp', 'oem tail lights', 'factory tail light'],
    summary: 'Honest OEM rear-lamp lookup row for stock-style repairs and subtle refresh questions.',
    priceRange: { min: 120, max: 520 },
    attributes: { install: 'bolt-on', oemStyle: true },
    resultType: 'parts-lookup',
    intentTags: ['replacement'],
    styleTags: ['factory-like', 'oem-like'],
    exactMatchPhrases: ['oem tail lights', 'factory tail light', 'tail lamp replacement'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use exact left/right and trim/package application data rather than assuming all WD Durango lamps interchange.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20tail%20lamp',
    sourceLabel: 'Mopar tail-lamp search (broad by necessity)',
  },
  {
    id: 'mopar-durango-third-brake-light-lookup',
    sku: 'MOP-DUR14-3RDBRK-LOOKUP',
    name: 'Third Brake Light / CHMSL Parts Lookup',
    brand: 'Mopar',
    category: 'lighting',
    keywords: ['lighting', 'third brake light', 'center brake light', 'chmsl', 'rear spoiler light', 'oem+'],
    summary: 'Specific lighting row for center high-mount brake-light searches so they do not collapse into generic rear-light results.',
    priceRange: { min: 58, max: 180 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use exact spoiler/hatch lamp application data because body-style details matter.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20third%20brake%20light',
    sourceLabel: 'Mopar CHMSL search (broad by necessity)',
  },
  {
    id: 'weathertech-durango-sunshade-kit',
    sku: 'WT-DUR14-SUNSHADE',
    name: 'Custom SunShade Kit',
    brand: 'WeatherTech',
    category: 'interior',
    keywords: ['interior', 'sunshade', 'window shade', 'heat', 'comfort', 'daily', 'family'],
    summary: 'More coverage-oriented sunshade direction for owners who want side and rear shade options, not just a windshield screen.',
    priceRange: { min: 140, max: 220 },
    attributes: { install: 'bolt-on', familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Grounded as a vehicle-specific WeatherTech shade family direction for the exact Durango record.' }],
    sourceUrl: 'https://www.weathertech.com/dodge/2014/durango/sunshade/',
    sourceLabel: 'WeatherTech 2014 Durango SunShade vehicle page',
  },
  {
    id: 'husky-durango-floor-liners',
    sku: 'HSK-DUR14-WX',
    name: 'WeatherBeater Floor Liner Set',
    brand: 'Husky Liners',
    category: 'interior',
    keywords: ['interior', 'floor liners', 'floor mats', 'all weather mats', 'winter', 'family', 'utility'],
    summary: 'Alternative all-weather floor-liner direction for buyers cross-shopping WeatherTech and similar heavy-duty protection options.',
    priceRange: { min: 170, max: 250 },
    attributes: { install: 'bolt-on', familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Seat/console layout matters; keep this tied to explicit 2014 Durango interior-floor applications.' }],
    sourceUrl: 'https://www.huskyliners.com/',
    sourceLabel: 'Husky Liners vehicle/catalog page (broad by necessity)',
  },
  {
    id: 'coverking-durango-seat-cover-lookup',
    sku: 'CVK-DUR14-SEAT-LOOKUP',
    name: 'Custom Seat Cover Lookup',
    brand: 'Coverking',
    category: 'interior',
    keywords: ['interior', 'seat covers', 'seat protection', 'pets', 'kids', 'daily', 'family'],
    summary: 'Alternative seat-cover direction for owners who care more about protection and material choice than faux-luxury styling.',
    priceRange: { min: 260, max: 640 },
    attributes: { install: 'moderate', familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Exact seat layout and row configuration matter, so keep this as a vehicle-specific lookup direction.' }],
    sourceUrl: 'https://coverking.com/collections/custom-seat-covers',
    sourceLabel: 'Coverking custom seat cover family page',
  },
  {
    id: 'dash-designs-durango-dash-cover',
    sku: 'DSD-DUR14-DASH',
    name: 'Custom Dash Cover',
    brand: 'Dash Designs',
    category: 'interior',
    keywords: ['interior', 'dash cover', 'dashboard cover', 'sun protection', 'oem+', 'daily'],
    summary: 'Small but useful interior-preservation item for cracked-dash prevention and glare control in older SUVs.',
    priceRange: { min: 58, max: 95 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Sensor/cutout details vary with trim and options, so keep purchase tied to exact dashboard layout.' }],
    sourceUrl: 'https://www.dashdesigns.com/',
    sourceLabel: 'Dash Designs family/catalog page (broad by necessity)',
  },
  {
    id: 'mopar-durango-cargo-cover-lookup',
    sku: 'MOP-DUR14-CARGOCOVER-LOOKUP',
    name: 'Cargo Cover / Tonneau Cover Lookup',
    brand: 'Mopar',
    category: 'interior',
    keywords: ['interior', 'cargo cover', 'privacy cover', 'tonneau cover', 'rear shade', 'road trip'],
    summary: 'Specific answer for owners wanting hidden cargo storage rather than a tray or deep liner.',
    priceRange: { min: 160, max: 320 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Cargo-cover fit depends on the exact cargo-area setup and installed trim pieces.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20cargo%20cover',
    sourceLabel: 'Mopar cargo-cover search (broad by necessity)',
  },
  {
    id: 'lloyd-durango-carpet-mats',
    sku: 'LLY-DUR14-CARPET',
    name: 'Custom Carpet Floor Mat Set',
    brand: 'Lloyd Mats',
    category: 'interior',
    keywords: ['interior', 'floor mats', 'carpet mats', 'oem+', 'luxury', 'daily', 'clean look'],
    summary: 'Carpet-mat direction for owners who want the interior to feel nicer rather than more rugged.',
    priceRange: { min: 155, max: 265 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Useful for OEM+ interior refresh searches where hard all-weather liners are not the desired look.' }],
    sourceUrl: 'https://www.lloydmatsstore.com/',
    sourceLabel: 'Lloyd Mats family/catalog page (broad by necessity)',
  },
  {
    id: 'garmin-mini-3-dash-cam',
    sku: 'GAR-MINI3',
    name: 'Dash Cam Mini 3',
    brand: 'Garmin',
    category: 'audio',
    keywords: ['audio', 'dash cam', 'dashcam', 'camera', 'safety', 'daily', 'road trip'],
    summary: 'Compact dash-cam direction that suits a family SUV without cluttering the windshield with a giant screen.',
    priceRange: { min: 140, max: 180 },
    attributes: { install: 'moderate', cargoImpact: 'none' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal dash cam, but a grounded Durango-friendly packaging choice because installation is adhesive/power-routing based rather than vehicle-specific.' }],
    sourceUrl: 'https://www.garmin.com/en-US/p/863792',
    sourceLabel: 'Garmin Dash Cam Mini 3 exact product page',
  },
  {
    id: 'kenwood-cmos-230-backup-camera',
    sku: 'KEN-CMOS230',
    name: 'CMOS-230 Universal Backup Camera',
    brand: 'Kenwood',
    category: 'audio',
    keywords: ['audio', 'backup camera', 'reverse camera', 'camera', 'parking', 'tech', 'daily'],
    summary: 'Simple backup-camera add-on direction for Durangos missing the visibility help owners now expect.',
    priceRange: { min: 88, max: 130 },
    attributes: { install: 'advanced', cargoImpact: 'none' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal camera hardware; the grounded part is the exact camera, while integration depends on the screen/head-unit path used in the SUV.' }],
    sourceUrl: 'https://www.kenwood.com/usa/car/cameras/cmos-230/',
    sourceLabel: 'Kenwood CMOS-230 exact product page',
  },
  {
    id: 'jbl-basspro-hub-powered-subwoofer',
    sku: 'JBL-BASSPROHUB',
    name: 'BassPro Hub Powered Subwoofer',
    brand: 'JBL',
    category: 'audio',
    keywords: ['audio', 'subwoofer', 'spare tire sub', 'bass', 'cargo friendly', 'road trip', 'daily'],
    summary: 'Cargo-friendly subwoofer direction because it uses the spare-tire well instead of consuming a big chunk of usable family cargo space.',
    priceRange: { min: 360, max: 470 },
    attributes: { install: 'advanced', cargoImpact: 'low' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal spare-tire-well style sub; grounded here because the Durango cargo-area use case strongly favors low-footprint bass solutions.' }],
    sourceUrl: 'https://www.jbl.com/car-subwoofers/BASSPRO+HUB.html',
    sourceLabel: 'JBL BassPro Hub exact product page',
  },
  {
    id: 'kicker-key-2004-mini-amp',
    sku: 'KIK-47KEY2004',
    name: 'KEY 200.4 Smart Amplifier',
    brand: 'KICKER',
    category: 'audio',
    keywords: ['audio', 'amp', 'amplifier', 'speaker upgrade', 'clarity', 'oem+', 'daily'],
    summary: 'Small smart amp direction for owners who want clearer audio and better speaker control without a giant custom install.',
    priceRange: { min: 260, max: 330 },
    attributes: { install: 'advanced', cargoImpact: 'none' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal amplifier product; the grounded fit direction is its small packaging for factory-radio-retention style installs.' }],
    sourceUrl: 'https://www.kicker.com/key-2004-4-channel-smart-amplifier',
    sourceLabel: 'KICKER KEY 200.4 exact product page',
  },
  {
    id: 'jbl-club-64c-speaker-set',
    sku: 'JBL-CLUB64C',
    name: 'Club 64C Component Speaker Set',
    brand: 'JBL',
    category: 'audio',
    keywords: ['audio', 'speakers', 'component speakers', 'door speakers', 'clarity', 'front stage', 'road trip'],
    summary: 'Speaker-upgrade direction for owners chasing cleaner detail and better front-stage sound than basic OEM speakers provide.',
    priceRange: { min: 110, max: 165 },
    attributes: { install: 'moderate', cargoImpact: 'none' },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal speaker product; verify mount depth, impedance, and bracket/connector needs for the exact Durango door application.' }],
    sourceUrl: 'https://www.jbl.com/car-speakers/CLUB64C.html',
    sourceLabel: 'JBL Club 64C exact product page',
  },
  {
    id: 'etrailer-durango-curt-class3-hitch',
    sku: 'CUR-13264',
    name: 'CURT Class III Trailer Hitch Receiver',
    brand: 'CURT',
    category: 'utility',
    keywords: ['utility', 'hitch', 'receiver hitch', 'tow hitch', 'bike rack', 'cargo carrier', 'towing'],
    summary: 'Popular Class III hitch direction for towing-light duty and hitch-mounted accessory use on the Durango.',
    priceRange: { min: 210, max: 330 },
    attributes: { install: 'advanced', towFocused: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use the explicit vehicle application on the hitch listing and respect actual Durango tow-equipment limits.' }],
    sourceUrl: 'https://www.etrailer.com/Trailer-Hitch/Dodge/Durango/2014/C13264.html',
    sourceLabel: 'etrailer CURT C13264 exact 2014 Durango hitch page',
  },
  {
    id: 'etrailer-durango-trailer-wiring-4pin',
    sku: 'TK-118617',
    name: 'T-One 4-Pole Trailer Wiring Harness',
    brand: 'Tekonsha',
    category: 'utility',
    keywords: ['utility', 'trailer wiring', '4 pin harness', 'tow wiring', 'towing', 'lighting harness'],
    summary: 'Specific trailer-wiring answer for light trailer and hitch-accessory lighting needs.',
    priceRange: { min: 48, max: 78 },
    attributes: { install: 'moderate', towFocused: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Grounded to the explicit 2014 Durango wiring-harness application page rather than a generic wiring suggestion.' }],
    sourceUrl: 'https://www.etrailer.com/Custom-Fit-Vehicle-Wiring/Dodge/Durango/2014/118617.html',
    sourceLabel: 'etrailer Tekonsha 118617 exact 2014 Durango wiring page',
  },
  {
    id: 'etrailer-durango-trailer-wiring-7way',
    sku: 'ETBC7L',
    name: '7-Way Upgrade / Adapter Kit',
    brand: 'etrailer',
    category: 'utility',
    keywords: ['utility', 'trailer wiring', '7 pin harness', '7 way', 'towing', 'brake controller'],
    summary: 'Supporting towing-wiring direction for owners stepping beyond a simple 4-flat toward brake-controller-compatible trailer setups.',
    priceRange: { min: 84, max: 120 },
    attributes: { install: 'advanced', towFocused: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal upgrade kit; grounded as a real towing-support path when paired with the correct Durango wiring base and controller plan.' }],
    sourceUrl: 'https://www.etrailer.com/Accessories-and-Parts/etrailer/ETBC7L.html',
    sourceLabel: 'etrailer ETBC7L exact product page',
  },
  {
    id: 'mopar-durango-running-boards-lookup',
    sku: 'MOP-DUR14-RBOARD-LOOKUP',
    name: 'Running Boards / Side Steps Lookup',
    brand: 'Mopar',
    category: 'utility',
    keywords: ['utility', 'running boards', 'side steps', 'step bars', 'family', 'daily', 'appearance'],
    summary: 'Specific side-step answer for people wanting easier entry, especially with kids, elderly passengers, or a mildly lifted tire look.',
    priceRange: { min: 360, max: 890 },
    attributes: { install: 'advanced', familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use explicit board/step application data because rocker trim and mounting details matter.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20running%20boards',
    sourceLabel: 'Mopar running-board search (broad by necessity)',
  },
  {
    id: 'yakima-loadwarrior-roof-basket',
    sku: 'YAK-8007070',
    name: 'LoadWarrior Roof Basket',
    brand: 'Yakima',
    category: 'utility',
    keywords: ['utility', 'roof basket', 'roof rack', 'cargo', 'outdoors', 'road trip', 'extra storage'],
    summary: 'Open-basket roof-storage direction for bulky gear that does not fit neatly inside a closed cargo box.',
    priceRange: { min: 520, max: 690 },
    attributes: { install: 'bolt-on', requiresCrossbars: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal basket that depends on installed crossbars and usable roof dimensions rather than naked-roof fitment.' }],
    sourceUrl: 'https://yakima.com/products/loadwarrior',
    sourceLabel: 'Yakima LoadWarrior exact product page',
  },
  {
    id: 'thule-camber-hitch-bike-rack',
    sku: 'THU-9056',
    name: 'Camber 4-Bike Hitch Rack',
    brand: 'Thule',
    category: 'utility',
    keywords: ['utility', 'bike rack', 'hitch rack', 'family', 'road trip', 'outdoors', 'hitch accessory'],
    summary: 'Grounded bike-rack direction for Durango owners using the SUV as a family adventure hauler rather than just a commuter.',
    priceRange: { min: 380, max: 520 },
    attributes: { install: 'bolt-on', requiresHitch: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal hitch-mount rack; safe recommendation depends on having a compatible receiver already installed.' }],
    sourceUrl: 'https://www.thule.com/en-us/bike-rack/hitch-bike-racks/thule-camber-4-_-9056',
    sourceLabel: 'Thule Camber 4 exact product page',
  },
  {
    id: 'etrailer-hitch-cargo-carrier',
    sku: 'CUR-18153',
    name: 'Steel Hitch Cargo Carrier',
    brand: 'CURT',
    category: 'utility',
    keywords: ['utility', 'cargo carrier', 'hitch cargo', 'extra storage', 'road trip', 'family', 'hitch accessory'],
    summary: 'Useful extra-storage answer when the third row is up and interior cargo room disappears.',
    priceRange: { min: 180, max: 260 },
    attributes: { install: 'bolt-on', requiresHitch: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Universal hitch carrier; grounded as a practical Durango cargo-expansion direction if a receiver is already fitted.' }],
    sourceUrl: 'https://www.etrailer.com/Hitch-Cargo-Carrier/CURT/C18153.html',
    sourceLabel: 'etrailer CURT C18153 exact product page',
  },
  {
    id: 'weathertech-durango-window-deflectors',
    sku: 'WT-DUR14-SWD',
    name: 'Side Window Deflectors',
    brand: 'WeatherTech',
    category: 'appearance',
    keywords: ['appearance', 'window deflectors', 'rain guards', 'visors', 'oem+', 'daily', 'road trip'],
    summary: 'Vehicle-specific side-window-deflector option for owners who want the rain-guard look with a cleaner direct source page than a generic accessory search.',
    priceRange: { min: 110, max: 165 },
    attributes: { install: 'bolt-on', oemStyle: true },
    resultType: 'accessory',
    intentTags: ['cosmetic', 'comfort'],
    styleTags: ['factory-like', 'subtle'],
    exactMatchPhrases: ['window deflectors', 'rain guards', 'window visors'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Keep to the explicit 2014 Durango side-window application page and actual door count/body opening layout.' }],
    sourceUrl: 'https://www.weathertech.com/dodge/2014/durango/side-window-deflectors/',
    sourceLabel: 'WeatherTech 2014 Durango Side Window Deflectors vehicle page',
  },
  {
    id: 'mopar-durango-window-deflectors-lookup',
    sku: 'MOP-DUR14-DEFLECTOR-LOOKUP',
    name: 'Side Window Air Deflector Lookup',
    brand: 'Mopar',
    category: 'appearance',
    keywords: ['appearance', 'window deflectors', 'rain guards', 'visors', 'oem+', 'daily', 'road trip'],
    summary: 'Specific answer for window-visor/rain-guard searches that suit a subtle OEM+ Durango build well when the buyer wants Mopar-first sourcing.',
    priceRange: { min: 90, max: 160 },
    attributes: { install: 'bolt-on', oemStyle: true },
    resultType: 'parts-lookup',
    intentTags: ['replacement', 'cosmetic'],
    exactMatchPhrases: ['window deflectors', 'rain guards', 'window visors'],
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Keep to explicit front/rear door application data and the actual body opening layout.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20air%20deflector',
    sourceLabel: 'Mopar window-deflector search (broad by necessity)',
  },
  {
    id: 'avs-durango-bugflector-ii',
    sku: 'AVS-25057',
    name: 'Bugflector II Hood Shield',
    brand: 'Auto Ventshade',
    category: 'appearance',
    keywords: ['appearance', 'hood deflector', 'bug shield', 'front protection', 'road trip', 'daily', 'oem+'],
    summary: 'Alternative hood-shield direction for owners wanting a more common aftermarket bug-deflector route than Mopar branding.',
    priceRange: { min: 68, max: 108 },
    attributes: { install: 'bolt-on', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use the explicit 2014 Durango application; AVS fitment should not be generalized across facelifts.' }],
    sourceUrl: 'https://realtruck.com/p/avs-bugflector-ii/',
    sourceLabel: 'AVS Bugflector II product family page',
  },
  {
    id: 'mopar-durango-grille-insert-lookup',
    sku: 'MOP-DUR14-GRILLE-LOOKUP',
    name: 'Factory Grille / Grille Insert Lookup',
    brand: 'Mopar',
    category: 'appearance',
    keywords: ['appearance', 'grille', 'front grille', 'grille insert', 'oem grille', 'oem+'],
    summary: 'OEM-style grille lookup row for stock replacement or subtle front-end cleanup questions.',
    priceRange: { min: 180, max: 620 },
    attributes: { install: 'moderate', oemStyle: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Front fascia and trim differences matter, so keep this as a VIN-backed parts-lookup direction.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20grille',
    sourceLabel: 'Mopar grille search (broad by necessity)',
  },
  {
    id: 'mopar-durango-cabin-filter-lookup',
    sku: 'MOP-DUR14-CABIN-LOOKUP',
    name: 'Cabin Air Filter Parts Lookup',
    brand: 'Mopar',
    category: 'maintenance',
    keywords: ['maintenance', 'cabin filter', 'cabin air filter', 'air quality', 'comfort', 'service'],
    summary: 'More explicit cabin-filter lookup row for practical service questions and recurring maintenance needs.',
    priceRange: { min: 18, max: 42 },
    attributes: { install: 'bolt-on', serviceItem: true, familyFriendly: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use exact Mopar/vehicle lookup because filter revisions and aftermarket cross-references can vary.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20cabin%20air%20filter',
    sourceLabel: 'Mopar cabin-filter search (broad by necessity)',
  },
  {
    id: 'mopar-durango-engine-air-filter-lookup',
    sku: 'MOP-DUR14-ENGAIR-LOOKUP',
    name: 'Engine Air Filter Parts Lookup',
    brand: 'Mopar',
    category: 'maintenance',
    keywords: ['maintenance', 'engine air filter', 'air filter', 'service', 'oem+', 'daily'],
    summary: 'More explicit stock-style engine-air-filter row for searchers who just want to service the SUV properly.',
    priceRange: { min: 20, max: 38 },
    attributes: { install: 'bolt-on', serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use exact engine application data and do not generalize across Hemi and Pentastar filter shapes.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20engine%20air%20filter',
    sourceLabel: 'Mopar engine-air-filter search (broad by necessity)',
  },
  {
    id: 'bosch-durango-icon-wipers',
    sku: 'BOS-ICON-DUR14',
    name: 'ICON Wiper Blade Pair',
    brand: 'Bosch',
    category: 'maintenance',
    keywords: ['maintenance', 'wipers', 'wiper blades', 'visibility', 'rain', 'winter', 'daily'],
    summary: 'Premium wiper-blade direction for drivers who just want the windshield to be handled properly in bad weather.',
    priceRange: { min: 42, max: 68 },
    attributes: { install: 'bolt-on', serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Blade length and rear-wiper details should still be confirmed for the exact Durango setup.' }],
    sourceUrl: 'https://www.boschautoparts.com/p/icon-wiper-blades',
    sourceLabel: 'Bosch ICON product family page',
  },
  {
    id: 'ngk-durango-iridium-spark-plugs',
    sku: 'NGK-LZFR5CI-11',
    name: 'Iridium IX Spark Plug Service Set',
    brand: 'NGK',
    category: 'maintenance',
    keywords: ['maintenance', 'spark plugs', 'tune up', 'service', '3.6 pentastar', 'engine refresh'],
    summary: 'Real-world tune-up service direction for Pentastar ownership questions where the right answer is maintenance, not mods.',
    priceRange: { min: 58, max: 96 },
    attributes: { install: 'advanced', serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Spark-plug choice should stay tied to the exact 3.6L Pentastar application and service interval plan.' }],
    sourceUrl: 'https://ngksparkplugs.com/en/products/spark-plugs/iridium-ix',
    sourceLabel: 'NGK Iridium IX product family page',
  },
  {
    id: 'mopar-durango-oil-filter-lookup',
    sku: 'MOP-DUR14-OILFILTER-LOOKUP',
    name: 'Oil Filter / Oil Change Parts Lookup',
    brand: 'Mopar',
    category: 'maintenance',
    keywords: ['maintenance', 'oil filter', 'oil change', 'service', 'engine maintenance', 'practical'],
    summary: 'Explicit oil-service lookup row so practical ownership searches can return the obvious maintenance answer.',
    priceRange: { min: 8, max: 26 },
    attributes: { install: 'bolt-on', serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Use exact Pentastar oil-filter lookup and oil-spec guidance for the real vehicle.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20oil%20filter',
    sourceLabel: 'Mopar oil-filter search (broad by necessity)',
  },
  {
    id: 'mopar-durango-battery-lookup',
    sku: 'MOP-DUR14-BATT-LOOKUP',
    name: 'Battery / AGM Battery Lookup',
    brand: 'Mopar',
    category: 'maintenance',
    keywords: ['maintenance', 'battery', 'agm battery', 'starting', 'winter', 'service', 'practical'],
    summary: 'Specific battery-service answer for Durangos that are aging into colder-weather starting issues.',
    priceRange: { min: 180, max: 360 },
    attributes: { install: 'moderate', serviceItem: true },
    fitments: [{ vehicleId: VEHICLE_ID, notes: 'Battery group size and AGM requirements should stay tied to the exact vehicle equipment.' }],
    sourceUrl: 'https://store.mopar.com/search?search_str=2014%20Dodge%20Durango%20battery',
    sourceLabel: 'Mopar battery search (broad by necessity)',
  },
]
