import { durangoVehicleNotes, durangoParts } from '@/lib/durango-grounded-data'

export type DemoVehicle = {
  id: string
  year: number
  make: string
  model: string
  trim?: string
  engine?: string
  drivetrain?: string
  platformNotes?: string[]
}

export type FitmentRecord = {
  vehicleId: string
  notes?: string
}

export type FitmentDemoCategory =
  | 'intake'
  | 'exhaust'
  | 'suspension'
  | 'brakes'
  | 'wheels'
  | 'engine'
  | 'lighting'
  | 'aero'
  | 'interior'
  | 'audio'
  | 'utility'
  | 'maintenance'
  | 'appearance'

export type FitmentIntentType = 'replacement' | 'aftermarket-upgrade' | 'cosmetic' | 'comfort' | 'utility' | 'maintenance' | 'tech'

export type FitmentResultType = 'oem-replacement' | 'aftermarket-upgrade' | 'accessory' | 'service-item' | 'parts-lookup' | 'universal'

export type FitmentDemoPart = {
  id: string
  sku: string
  name: string
  brand: string
  category: FitmentDemoCategory
  keywords: string[]
  summary: string
  priceRange: { min: number; max: number }
  attributes?: Record<string, string | number | boolean>
  intentTags?: FitmentIntentType[]
  resultType?: FitmentResultType
  styleTags?: string[]
  exactMatchPhrases?: string[]
  fitments: FitmentRecord[]
  sourceUrl?: string
  sourceLabel?: string
}

// Demo DB used to prove the grounded fitment architecture. The search helper is only allowed
// to rank and explain parts that exist here and that have an explicit fitment match.
export const demoVehicles: DemoVehicle[] = [
  {
    id: '2018-honda-civic-si-sedan-15t-fwd',
    year: 2018,
    make: 'Honda',
    model: 'Civic Si',
    trim: 'Sedan',
    engine: '1.5T',
    drivetrain: 'FWD',
  },
  {
    id: '2020-subaru-wrx-base-20t-awd',
    year: 2020,
    make: 'Subaru',
    model: 'WRX',
    trim: 'Base',
    engine: '2.0T',
    drivetrain: 'AWD',
  },
  {
    id: '2016-ford-mustang-gt-coupe-50-rwd',
    year: 2016,
    make: 'Ford',
    model: 'Mustang GT',
    trim: 'Coupe',
    engine: '5.0',
    drivetrain: 'RWD',
  },
  {
    id: '2019-volkswagen-gti-autobahn-20t-fwd',
    year: 2019,
    make: 'Volkswagen',
    model: 'GTI',
    trim: 'Autobahn',
    engine: '2.0T',
    drivetrain: 'FWD',
  },
  {
    id: '2023-toyota-gr86-premium-24-rwd',
    year: 2023,
    make: 'Toyota',
    model: 'GR86',
    trim: 'Premium',
    engine: '2.4',
    drivetrain: 'RWD',
  },
  {
    id: '2021-bmw-m340i-xdrive-sedan-30t-awd',
    year: 2021,
    make: 'BMW',
    model: 'M340i',
    trim: 'xDrive Sedan',
    engine: '3.0T',
    drivetrain: 'AWD',
  },
  {
    id: '2015-mazda-mx-5-miata-club-20-rwd',
    year: 2015,
    make: 'Mazda',
    model: 'MX-5 Miata',
    trim: 'Club',
    engine: '2.0',
    drivetrain: 'RWD',
  },
  {
    id: '2017-chevrolet-camaro-ss-coupe-62-rwd',
    year: 2017,
    make: 'Chevrolet',
    model: 'Camaro SS',
    trim: 'Coupe',
    engine: '6.2',
    drivetrain: 'RWD',
  },
  {
    id: '2014-dodge-durango-limited-36-awd',
    year: 2014,
    make: 'Dodge',
    model: 'Durango',
    trim: 'Limited',
    engine: '3.6L',
    drivetrain: 'AWD',
    platformNotes: durangoVehicleNotes,
  },
]

export const demoParts: FitmentDemoPart[] = [
  {
    id: 'prl-civic-si-intake',
    sku: 'PRL-HC10-INT',
    name: 'High-Volume Intake System',
    brand: 'PRL Motorsports',
    category: 'intake',
    keywords: ['intake', 'air intake', 'cold air', 'sound', 'spool', 'turbo noise', 'response'],
    summary: 'Bolt-on intake for 10th gen Civic Si with better induction sound and airflow.',
    priceRange: { min: 395, max: 420 },
    attributes: { install: 'bolt-on', tuneRequired: false },
    fitments: [{ vehicleId: '2018-honda-civic-si-sedan-15t-fwd', notes: '10th gen Si 1.5T only' }],
  },
  {
    id: 'remark-civic-si-catback',
    sku: 'RMK-FC1-CB',
    name: 'Cat-Back Exhaust',
    brand: 'Remark',
    category: 'exhaust',
    keywords: ['exhaust', 'catback', 'sound', 'loud', 'tone', 'aggressive'],
    summary: 'Stainless cat-back for Civic Si with a more aggressive sound profile.',
    priceRange: { min: 845, max: 910 },
    attributes: { install: 'moderate', loudness: 'medium-high' },
    fitments: [{ vehicleId: '2018-honda-civic-si-sedan-15t-fwd' }],
  },
  {
    id: 'hawk-civic-si-pads',
    sku: 'HWK-HPS-HC10',
    name: 'HPS 5.0 Performance Brake Pads',
    brand: 'Hawk',
    category: 'brakes',
    keywords: ['brakes', 'pads', 'stopping', 'daily', 'spirited', 'street', 'better brakes', 'more bite'],
    summary: 'Street-friendly pad upgrade with more bite than OEM.',
    priceRange: { min: 165, max: 190 },
    attributes: { install: 'bolt-on', trackBias: false },
    fitments: [{ vehicleId: '2018-honda-civic-si-sedan-15t-fwd' }],
  },
  {
    id: 'eibach-civic-si-springs',
    sku: 'EIB-FC1-PRO',
    name: 'Pro-Kit Lowering Springs',
    brand: 'Eibach',
    category: 'suspension',
    keywords: ['springs', 'lower', 'stance', 'handling', 'street', 'daily'],
    summary: 'Moderate drop spring kit for Civic Si with a mild street-friendly stance.',
    priceRange: { min: 299, max: 340 },
    attributes: { install: 'moderate', alignmentRequired: true },
    fitments: [{ vehicleId: '2018-honda-civic-si-sedan-15t-fwd', notes: 'Sedan fitment in this demo dataset' }],
  },
  {
    id: 'enkei-civic-si-ts5-wheel',
    sku: 'ENK-TS5-18X85-5X114-FC1',
    name: 'TS-5 18x8.5 Wheel Set',
    brand: 'Enkei',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'rim', 'rims', 'lightweight', 'street', 'handling'],
    summary: 'Lightweight 18x8.5 wheel setup commonly sized for the 10th gen Civic Si.',
    priceRange: { min: 1180, max: 1280 },
    attributes: { finish: 'matte bronze', install: 'bolt-on' },
    fitments: [{ vehicleId: '2018-honda-civic-si-sedan-15t-fwd', notes: 'Demo assumes a direct 5x114.3 fitment package' }],
  },
  {
    id: 'hirev-civic-si-headlights',
    sku: 'HRV-FC1-LED-HL',
    name: 'LED Headlight Assembly',
    brand: 'HiRev Sports',
    category: 'lighting',
    keywords: ['headlight', 'lights', 'led', 'lighting', 'appearance'],
    summary: 'LED headlight assembly upgrade for a sharper front-end look.',
    priceRange: { min: 690, max: 760 },
    attributes: { install: 'moderate', dotCompliant: false },
    fitments: [{ vehicleId: '2018-honda-civic-si-sedan-15t-fwd', notes: 'Aftermarket housing; check local lighting regulations' }],
  },
  {
    id: '27won-civic-si-downpipe',
    sku: '27W-FC1-DP',
    name: 'High-Flow Downpipe',
    brand: '27WON',
    category: 'engine',
    keywords: ['engine', 'power', 'turbo', 'response', 'performance'],
    summary: 'High-flow downpipe option for the L15 turbo Civic platform.',
    priceRange: { min: 495, max: 545 },
    attributes: { install: 'advanced', tuneRequired: true },
    fitments: [{ vehicleId: '2018-honda-civic-si-sedan-15t-fwd', notes: 'For off-road/track use considerations; tune support recommended' }],
  },
  {
    id: 'seibon-civic-si-spoiler',
    sku: 'SEI-FC1-CF-TRUNK',
    name: 'Carbon Trunk Spoiler',
    brand: 'Seibon',
    category: 'aero',
    keywords: ['aero', 'spoiler', 'wing', 'style', 'appearance'],
    summary: 'Low-profile carbon spoiler for a cleaner rear-end aero look.',
    priceRange: { min: 285, max: 340 },
    attributes: { install: 'bolt-on', finish: 'carbon fiber' },
    fitments: [{ vehicleId: '2018-honda-civic-si-sedan-15t-fwd' }],
  },
  {
    id: 'fortune-wrx-coilovers',
    sku: 'F500-WRX-VA',
    name: '500 Series Coilovers',
    brand: 'Fortune Auto',
    category: 'suspension',
    keywords: ['coilovers', 'suspension', 'handling', 'stance', 'lower', 'track'],
    summary: 'Height-adjustable coilover kit for VA WRX.',
    priceRange: { min: 1899, max: 1999 },
    attributes: { install: 'advanced', alignmentRequired: true },
    fitments: [{ vehicleId: '2020-subaru-wrx-base-20t-awd' }],
  },
  {
    id: 'grimmspeed-wrx-intake',
    sku: 'GRM-WRX-INT',
    name: 'Stealthbox Intake',
    brand: 'GrimmSpeed',
    category: 'intake',
    keywords: ['intake', 'airbox', 'sound', 'turbo', 'response'],
    summary: 'Closed-box intake for the FA20 WRX platform.',
    priceRange: { min: 545, max: 595 },
    attributes: { install: 'bolt-on', tuneRequired: true },
    fitments: [{ vehicleId: '2020-subaru-wrx-base-20t-awd', notes: 'Tune recommended/required by manufacturer' }],
  },
  {
    id: 'awe-wrx-catback',
    sku: 'AWE-WRX-TRK',
    name: 'Track Edition Cat-Back',
    brand: 'AWE',
    category: 'exhaust',
    keywords: ['exhaust', 'catback', 'loud', 'sound', 'track', 'aggressive'],
    summary: 'Straight-through cat-back for WRX with very aggressive volume.',
    priceRange: { min: 1295, max: 1395 },
    attributes: { install: 'moderate', loudness: 'high' },
    fitments: [{ vehicleId: '2020-subaru-wrx-base-20t-awd' }],
  },
  {
    id: 'stoptech-wrx-slotted-rotors',
    sku: 'STP-VA-ROT',
    name: 'Sport Slotted Rotor Set',
    brand: 'StopTech',
    category: 'brakes',
    keywords: ['brakes', 'rotor', 'rotors', 'stopping', 'street', 'track'],
    summary: 'Direct-fit slotted rotors for a sharper pedal feel and better heat management.',
    priceRange: { min: 420, max: 470 },
    attributes: { install: 'moderate', trackBias: true },
    fitments: [{ vehicleId: '2020-subaru-wrx-base-20t-awd' }],
  },
  {
    id: 'enkei-wrx-raijin-wheel',
    sku: 'ENK-RAIJIN-18X95-VA',
    name: 'Raijin 18x9.5 Wheel Set',
    brand: 'Enkei',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'rim', 'lightweight', 'handling', 'stance'],
    summary: 'Popular 18x9.5 wheel spec for VA WRX street and track-style builds.',
    priceRange: { min: 1320, max: 1450 },
    attributes: { finish: 'hyper silver', install: 'bolt-on' },
    fitments: [{ vehicleId: '2020-subaru-wrx-base-20t-awd', notes: 'Demo fitment assumes the listed WRX bolt pattern and hub spec' }],
  },
  {
    id: 'olm-wrx-tail-lights',
    sku: 'OLM-VA-LED-TL',
    name: 'Sequential LED Tail Lights',
    brand: 'OLM',
    category: 'lighting',
    keywords: ['lights', 'led', 'lighting', 'appearance', 'tail lights'],
    summary: 'LED tail light set with a more modern appearance for the VA chassis.',
    priceRange: { min: 435, max: 480 },
    attributes: { install: 'bolt-on' },
    fitments: [{ vehicleId: '2020-subaru-wrx-base-20t-awd' }],
  },
  {
    id: 'cobb-wrx-accessport',
    sku: 'COBB-AP3-SUB-004',
    name: 'Accessport V3',
    brand: 'COBB',
    category: 'engine',
    keywords: ['engine', 'power', 'performance', 'tune', 'response'],
    summary: 'Handheld tuning platform commonly used on the FA20 WRX.',
    priceRange: { min: 675, max: 725 },
    attributes: { install: 'bolt-on', tuneRequired: false },
    fitments: [{ vehicleId: '2020-subaru-wrx-base-20t-awd', notes: 'Device fitment only; calibration choice still matters' }],
  },
  {
    id: 'olm-wrx-front-lip',
    sku: 'OLM-VA-CS-LIP',
    name: 'CS Style Front Lip',
    brand: 'OLM',
    category: 'aero',
    keywords: ['aero', 'lip', 'splitter', 'style', 'appearance', 'look more aggressive', 'front lip'],
    summary: 'Front lip that gives the VA WRX a more aggressive lower front profile.',
    priceRange: { min: 249, max: 299 },
    attributes: { install: 'bolt-on', material: 'urethane' },
    fitments: [{ vehicleId: '2020-subaru-wrx-base-20t-awd' }],
  },
  {
    id: 'ford-performance-mustang-intake',
    sku: 'FP-MGT-CAI',
    name: 'Cold Air Intake Kit',
    brand: 'Ford Performance',
    category: 'intake',
    keywords: ['intake', 'cold air', 'sound', 'power', 'naturally aspirated', 'response'],
    summary: 'Factory-backed intake kit for S550 Mustang GT 5.0.',
    priceRange: { min: 429, max: 479 },
    attributes: { install: 'bolt-on', tuneRequired: false },
    fitments: [{ vehicleId: '2016-ford-mustang-gt-coupe-50-rwd' }],
  },
  {
    id: 'borla-mustang-axleback',
    sku: 'BOR-S550-ATAK',
    name: 'ATAK Axle-Back Exhaust',
    brand: 'Borla',
    category: 'exhaust',
    keywords: ['exhaust', 'axle-back', 'loud', 'sound', 'v8', 'aggressive'],
    summary: 'Aggressive axle-back exhaust for the S550 Mustang GT.',
    priceRange: { min: 980, max: 1080 },
    attributes: { install: 'bolt-on', loudness: 'high' },
    fitments: [{ vehicleId: '2016-ford-mustang-gt-coupe-50-rwd' }],
  },
  {
    id: 'steeda-mustang-springs',
    sku: 'STD-S550-SPR',
    name: 'Sport Lowering Springs',
    brand: 'Steeda',
    category: 'suspension',
    keywords: ['springs', 'lower', 'stance', 'handling', 'street'],
    summary: 'Street-oriented lowering spring package for the S550 chassis.',
    priceRange: { min: 329, max: 379 },
    attributes: { install: 'moderate', alignmentRequired: true },
    fitments: [{ vehicleId: '2016-ford-mustang-gt-coupe-50-rwd' }],
  },
  {
    id: 'powerstop-mustang-bbk',
    sku: 'PWR-S550-BBK',
    name: 'Front Big Brake Kit',
    brand: 'PowerStop',
    category: 'brakes',
    keywords: ['brakes', 'big brake', 'stopping', 'track', 'street'],
    summary: 'Larger front brake package for improved repeated stopping performance.',
    priceRange: { min: 1495, max: 1645 },
    attributes: { install: 'advanced', trackBias: true },
    fitments: [{ vehicleId: '2016-ford-mustang-gt-coupe-50-rwd' }],
  },
  {
    id: 'velgen-mustang-wheel-set',
    sku: 'VLG-VMB7-19X10-S550',
    name: 'VMB7 19x10 Wheel Set',
    brand: 'Velgen',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'rim', 'rims', 'stance', 'appearance'],
    summary: 'Wide 19-inch wheel package for a more aggressive S550 stance.',
    priceRange: { min: 1720, max: 1890 },
    attributes: { finish: 'gloss gunmetal', install: 'bolt-on' },
    fitments: [{ vehicleId: '2016-ford-mustang-gt-coupe-50-rwd' }],
  },
  {
    id: 'roush-mustang-active-exhaust-kit',
    sku: 'RSH-S550-ACT',
    name: 'Active Exhaust Valve Kit',
    brand: 'Roush',
    category: 'engine',
    keywords: ['engine', 'performance', 'sound', 'street', 'daily'],
    summary: 'Valve control package that helps balance daily drivability with V8 sound control.',
    priceRange: { min: 395, max: 450 },
    attributes: { install: 'moderate', loudness: 'medium' },
    fitments: [{ vehicleId: '2016-ford-mustang-gt-coupe-50-rwd', notes: 'Used here as an exhaust-control supporting item for the demo' }],
  },
  {
    id: 'mp-concepts-mustang-headlights',
    sku: 'MPC-S550-HL',
    name: 'LED Projector Headlights',
    brand: 'MP Concepts',
    category: 'lighting',
    keywords: ['headlight', 'lights', 'led', 'lighting', 'appearance'],
    summary: 'Updated projector-style LED headlights for an S550 refresh look.',
    priceRange: { min: 610, max: 690 },
    attributes: { install: 'moderate' },
    fitments: [{ vehicleId: '2016-ford-mustang-gt-coupe-50-rwd' }],
  },
  {
    id: 'mp-concepts-mustang-front-splitter',
    sku: 'MPC-S550-SPL',
    name: 'Front Splitter Kit',
    brand: 'MP Concepts',
    category: 'aero',
    keywords: ['aero', 'splitter', 'lip', 'style', 'appearance'],
    summary: 'Front splitter for a more planted, track-inspired Mustang look.',
    priceRange: { min: 219, max: 275 },
    attributes: { install: 'bolt-on', material: 'abs' },
    fitments: [{ vehicleId: '2016-ford-mustang-gt-coupe-50-rwd' }],
  },
  {
    id: 'apr-gti-intake',
    sku: 'APR-MQB-INT',
    name: 'Open PEX Intake System',
    brand: 'APR',
    category: 'intake',
    keywords: ['intake', 'air intake', 'turbo', 'sound', 'response'],
    summary: 'Open intake system for the MQB GTI platform with more induction sound.',
    priceRange: { min: 365, max: 420 },
    attributes: { install: 'bolt-on', tuneRequired: false },
    fitments: [{ vehicleId: '2019-volkswagen-gti-autobahn-20t-fwd' }],
  },
  {
    id: 'clubsport-gti-catback',
    sku: 'AWE-MK7-CB',
    name: 'Touring Cat-Back Exhaust',
    brand: 'AWE',
    category: 'exhaust',
    keywords: ['exhaust', 'catback', 'sound', 'daily', 'quiet'],
    summary: 'Touring-style cat-back aimed at a deeper tone without excessive drone.',
    priceRange: { min: 1195, max: 1295 },
    attributes: { install: 'moderate', loudness: 'medium' },
    fitments: [{ vehicleId: '2019-volkswagen-gti-autobahn-20t-fwd' }],
  },
  {
    id: 'bilstein-gti-coilovers',
    sku: 'BIL-MQB-B14',
    name: 'B14 PSS Coilover Kit',
    brand: 'Bilstein',
    category: 'suspension',
    keywords: ['coilovers', 'suspension', 'handling', 'lower', 'street'],
    summary: 'Street-performance coilover setup for the Mk7 GTI chassis.',
    priceRange: { min: 1499, max: 1599 },
    attributes: { install: 'advanced', alignmentRequired: true },
    fitments: [{ vehicleId: '2019-volkswagen-gti-autobahn-20t-fwd' }],
  },
  {
    id: 'neuspeed-gti-wheel-set',
    sku: 'NSD-RSE10-18X85-MK7',
    name: 'RSe10 18x8.5 Wheel Set',
    brand: 'Neuspeed',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'lightweight', 'handling', 'street'],
    summary: 'Lightweight flow-formed wheels sized for the Mk7 GTI.',
    priceRange: { min: 1580, max: 1690 },
    attributes: { finish: 'satin bronze', install: 'bolt-on' },
    fitments: [{ vehicleId: '2019-volkswagen-gti-autobahn-20t-fwd' }],
  },
  {
    id: 'helix-gti-headlights',
    sku: 'HLX-MK7-LP',
    name: 'LED Headlight Upgrade',
    brand: 'Helix',
    category: 'lighting',
    keywords: ['headlight', 'lights', 'led', 'lighting', 'appearance'],
    summary: 'Aftermarket LED headlight set to modernize base or halogen-style lighting.',
    priceRange: { min: 780, max: 860 },
    attributes: { install: 'moderate' },
    fitments: [{ vehicleId: '2019-volkswagen-gti-autobahn-20t-fwd' }],
  },
  {
    id: 'apr-gti-stage1-tune',
    sku: 'APR-MQB-STG1',
    name: 'Stage 1 ECU Tune',
    brand: 'APR',
    category: 'engine',
    keywords: ['engine', 'power', 'performance', 'tune', 'response'],
    summary: 'Off-the-shelf Stage 1 ECU calibration path for the Mk7 GTI platform.',
    priceRange: { min: 499, max: 549 },
    attributes: { install: 'software', tuneRequired: false },
    fitments: [{ vehicleId: '2019-volkswagen-gti-autobahn-20t-fwd', notes: 'Calibration support depends on ECU box code and fuel quality' }],
  },
  {
    id: 'maxton-gti-front-lip',
    sku: 'MAX-MK75-LIP',
    name: 'Front Splitter Lip',
    brand: 'Maxton Design',
    category: 'aero',
    keywords: ['aero', 'lip', 'splitter', 'style', 'appearance'],
    summary: 'Gloss-black front lip for a sharper Mk7 GTI front-end treatment.',
    priceRange: { min: 289, max: 335 },
    attributes: { install: 'bolt-on', material: 'abs' },
    fitments: [{ vehicleId: '2019-volkswagen-gti-autobahn-20t-fwd' }],
  },
  {
    id: 'hks-gr86-intake',
    sku: 'HKS-ZN8-INT',
    name: 'Cold Air Intake',
    brand: 'HKS',
    category: 'intake',
    keywords: ['intake', 'cold air', 'sound', 'response', 'naturally aspirated'],
    summary: 'Intake upgrade for the GR86 with improved induction tone and sharper response.',
    priceRange: { min: 455, max: 520 },
    attributes: { install: 'bolt-on', tuneRequired: false },
    fitments: [{ vehicleId: '2023-toyota-gr86-premium-24-rwd' }],
  },
  {
    id: 'greddy-gr86-catback',
    sku: 'GRD-ZN8-CB',
    name: 'Supreme SP Cat-Back',
    brand: 'GReddy',
    category: 'exhaust',
    keywords: ['exhaust', 'catback', 'sound', 'daily', 'tone'],
    summary: 'Balanced cat-back exhaust for the GR86 with a sportier tone than stock.',
    priceRange: { min: 1245, max: 1345 },
    attributes: { install: 'moderate', loudness: 'medium' },
    fitments: [{ vehicleId: '2023-toyota-gr86-premium-24-rwd' }],
  },
  {
    id: 'tein-gr86-coilovers',
    sku: 'TEI-ZN8-FLEX',
    name: 'FLEX Z Coilovers',
    brand: 'Tein',
    category: 'suspension',
    keywords: ['coilovers', 'suspension', 'handling', 'lower', 'street', 'stance'],
    summary: 'Entry-friendly adjustable coilover kit for GR86 street builds.',
    priceRange: { min: 1050, max: 1175 },
    attributes: { install: 'advanced', alignmentRequired: true },
    fitments: [{ vehicleId: '2023-toyota-gr86-premium-24-rwd' }],
  },
  {
    id: 'projectmu-gr86-pads',
    sku: 'PMU-ZN8-PS',
    name: 'HC+ Brake Pad Set',
    brand: 'Project Mu',
    category: 'brakes',
    keywords: ['brakes', 'pads', 'track', 'stopping', 'street'],
    summary: 'Higher-temp pad compound suited to spirited street and occasional track use.',
    priceRange: { min: 245, max: 290 },
    attributes: { install: 'bolt-on', trackBias: true },
    fitments: [{ vehicleId: '2023-toyota-gr86-premium-24-rwd' }],
  },
  {
    id: 'gramlights-gr86-wheel-set',
    sku: 'RAYS-57DR-18X95-ZN8',
    name: '57DR 18x9.5 Wheel Set',
    brand: 'Gram Lights',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'rim', 'lightweight', 'stance', 'track'],
    summary: 'Aggressive but common enthusiast wheel size for GR86/BRZ builds.',
    priceRange: { min: 2140, max: 2290 },
    attributes: { finish: 'matte graphite', install: 'bolt-on' },
    fitments: [{ vehicleId: '2023-toyota-gr86-premium-24-rwd', notes: 'Demo assumes a direct-fit package without spacer dependence' }],
  },
  {
    id: 'olm-gr86-tail-lights',
    sku: 'OLM-ZN8-TL',
    name: 'LED Tail Light Set',
    brand: 'OLM',
    category: 'lighting',
    keywords: ['lights', 'led', 'lighting', 'appearance', 'tail lights'],
    summary: 'LED tail lamp set for a darker, more modern rear-end look.',
    priceRange: { min: 419, max: 469 },
    attributes: { install: 'bolt-on' },
    fitments: [{ vehicleId: '2023-toyota-gr86-premium-24-rwd' }],
  },
  {
    id: 'ecutek-gr86-tune',
    sku: 'ECT-ZN8-TUNE',
    name: 'ECUtek Tuning License',
    brand: 'ECUtek',
    category: 'engine',
    keywords: ['engine', 'power', 'performance', 'tune', 'response'],
    summary: 'Tuning license used for custom calibration work on the FA24 platform.',
    priceRange: { min: 350, max: 425 },
    attributes: { install: 'software', tuneRequired: false },
    fitments: [{ vehicleId: '2023-toyota-gr86-premium-24-rwd', notes: 'License only; custom tune service is separate' }],
  },
  {
    id: 'apr-gr86-front-lip',
    sku: 'APR-ZN8-CW-01',
    name: 'Carbon Front Air Dam',
    brand: 'APR Performance',
    category: 'aero',
    keywords: ['aero', 'splitter', 'lip', 'track', 'appearance'],
    summary: 'Carbon front air dam for a lower, more purposeful GR86 front profile.',
    priceRange: { min: 995, max: 1095 },
    attributes: { install: 'advanced', material: 'carbon fiber' },
    fitments: [{ vehicleId: '2023-toyota-gr86-premium-24-rwd' }],
  },
  {
    id: 'dinan-m340i-intake',
    sku: 'DIN-G20-INT',
    name: 'Carbon Fiber Intake System',
    brand: 'Dinan',
    category: 'intake',
    keywords: ['intake', 'sound', 'turbo', 'response', 'performance'],
    summary: 'Premium intake setup for the B58-powered G20 M340i.',
    priceRange: { min: 1299, max: 1399 },
    attributes: { install: 'moderate', tuneRequired: false },
    fitments: [{ vehicleId: '2021-bmw-m340i-xdrive-sedan-30t-awd' }],
  },
  {
    id: 'awe-m340i-exhaust',
    sku: 'AWE-G20-TRK',
    name: 'Track Edition Exhaust',
    brand: 'AWE',
    category: 'exhaust',
    keywords: ['exhaust', 'sound', 'aggressive', 'loud', 'tone'],
    summary: 'Freer-flowing exhaust system for the G20 M340i with a sharper tone.',
    priceRange: { min: 1995, max: 2145 },
    attributes: { install: 'moderate', loudness: 'medium-high' },
    fitments: [{ vehicleId: '2021-bmw-m340i-xdrive-sedan-30t-awd' }],
  },
  {
    id: 'kw-m340i-hasp',
    sku: 'KW-G20-HAS',
    name: 'Height Adjustable Spring Kit',
    brand: 'KW',
    category: 'suspension',
    keywords: ['suspension', 'springs', 'lower', 'stance', 'street', 'handling'],
    summary: 'Height-adjustable spring setup for a mild premium drop without going full coilover.',
    priceRange: { min: 999, max: 1125 },
    attributes: { install: 'advanced', alignmentRequired: true },
    fitments: [{ vehicleId: '2021-bmw-m340i-xdrive-sedan-30t-awd' }],
  },
  {
    id: 'ebc-m340i-pads-rotors',
    sku: 'EBC-G20-USR',
    name: 'Yellowstuff Pads + USR Rotors',
    brand: 'EBC',
    category: 'brakes',
    keywords: ['brakes', 'pads', 'rotor', 'stopping', 'street'],
    summary: 'Matched pad and rotor package for better street bite and heat handling.',
    priceRange: { min: 890, max: 980 },
    attributes: { install: 'moderate', trackBias: false },
    fitments: [{ vehicleId: '2021-bmw-m340i-xdrive-sedan-30t-awd' }],
  },
  {
    id: 'hre-m340i-wheel-set',
    sku: 'HRE-FF11-20X9-G20',
    name: 'FlowForm FF11 Wheel Set',
    brand: 'HRE',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'rim', 'appearance', 'street', 'stance'],
    summary: 'Premium FlowForm wheel package sized for the G20 chassis.',
    priceRange: { min: 2680, max: 2890 },
    attributes: { finish: 'tarmac', install: 'bolt-on' },
    fitments: [{ vehicleId: '2021-bmw-m340i-xdrive-sedan-30t-awd' }],
  },
  {
    id: 'ind-m340i-laser-fogs',
    sku: 'IND-G20-YEL',
    name: 'Yellow DRL / Light Film Kit',
    brand: 'IND',
    category: 'lighting',
    keywords: ['lights', 'lighting', 'appearance', 'yellow', 'film'],
    summary: 'Appearance-oriented yellow light film kit for a more motorsport-inspired front look.',
    priceRange: { min: 79, max: 109 },
    attributes: { install: 'bolt-on' },
    fitments: [{ vehicleId: '2021-bmw-m340i-xdrive-sedan-30t-awd' }],
  },
  {
    id: 'bootmod3-m340i-tune',
    sku: 'BM3-B58-G20',
    name: 'bootmod3 OTS Tune License',
    brand: 'bootmod3',
    category: 'engine',
    keywords: ['engine', 'power', 'performance', 'tune', 'response'],
    summary: 'Flash tuning license for the B58 platform with staged OTS calibrations.',
    priceRange: { min: 595, max: 675 },
    attributes: { install: 'software', tuneRequired: false },
    fitments: [{ vehicleId: '2021-bmw-m340i-xdrive-sedan-30t-awd', notes: 'Calibration availability may vary by DME unlock status' }],
  },
  {
    id: '3d-m340i-spoiler',
    sku: '3D-G20-TRUNK',
    name: 'Carbon Trunk Spoiler',
    brand: '3D Design',
    category: 'aero',
    keywords: ['aero', 'spoiler', 'style', 'appearance'],
    summary: 'Subtle carbon trunk spoiler for a cleaner OEM+ rear aero treatment.',
    priceRange: { min: 525, max: 610 },
    attributes: { install: 'bolt-on', material: 'carbon fiber' },
    fitments: [{ vehicleId: '2021-bmw-m340i-xdrive-sedan-30t-awd' }],
  },
  {
    id: 'goodwin-miata-exhaust',
    sku: 'GWR-ND-RACE',
    name: 'Race Single Exhaust',
    brand: 'Good-Win Racing',
    category: 'exhaust',
    keywords: ['exhaust', 'sound', 'daily', 'lightweight', 'tone'],
    summary: 'Popular lightweight exhaust for ND Miata owners who want more personality.',
    priceRange: { min: 525, max: 625 },
    attributes: { install: 'bolt-on', loudness: 'medium' },
    fitments: [{ vehicleId: '2015-mazda-mx-5-miata-club-20-rwd' }],
  },
  {
    id: 'ohlins-miata-coilovers',
    sku: 'OHL-ND-RT',
    name: 'Road & Track Coilovers',
    brand: 'Ohlins',
    category: 'suspension',
    keywords: ['coilovers', 'handling', 'street', 'track', 'suspension'],
    summary: 'Premium dual-purpose coilover kit for the ND Miata platform.',
    priceRange: { min: 2895, max: 3095 },
    attributes: { install: 'advanced', alignmentRequired: true },
    fitments: [{ vehicleId: '2015-mazda-mx-5-miata-club-20-rwd' }],
  },
  {
    id: 'flyinmiata-miata-sway-bars',
    sku: 'FM-ND-SWB',
    name: 'Front and Rear Sway Bar Kit',
    brand: 'Flyin Miata',
    category: 'suspension',
    keywords: ['suspension', 'handling', 'street', 'track', 'response'],
    summary: 'Matched sway bar package for a flatter, sharper ND Miata feel.',
    priceRange: { min: 499, max: 560 },
    attributes: { install: 'moderate' },
    fitments: [{ vehicleId: '2015-mazda-mx-5-miata-club-20-rwd' }],
  },
  {
    id: 'wilwood-miata-bbk',
    sku: 'WLW-ND-FBK',
    name: 'Dynapro Front Big Brake Kit',
    brand: 'Wilwood',
    category: 'brakes',
    keywords: ['brakes', 'big brake', 'track', 'stopping'],
    summary: 'Front brake upgrade for track-focused or repeated hard-use ND driving.',
    priceRange: { min: 1399, max: 1549 },
    attributes: { install: 'advanced', trackBias: true },
    fitments: [{ vehicleId: '2015-mazda-mx-5-miata-club-20-rwd' }],
  },
  {
    id: 'advanti-miata-wheel-set',
    sku: 'ADV-STORM-17X8-ND',
    name: 'Storm S1 17x8 Wheel Set',
    brand: 'Advanti Racing',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'lightweight', 'handling', 'track'],
    summary: 'Very popular lightweight wheel option for the ND chassis.',
    priceRange: { min: 1160, max: 1240 },
    attributes: { finish: 'hyper silver', install: 'bolt-on' },
    fitments: [{ vehicleId: '2015-mazda-mx-5-miata-club-20-rwd' }],
  },
  {
    id: 'mx5things-miata-drl-kit',
    sku: 'MX5-ND-DRL',
    name: 'Sequential DRL Harness Kit',
    brand: 'MX5things',
    category: 'lighting',
    keywords: ['lights', 'lighting', 'appearance', 'drl'],
    summary: 'Harness-based DRL enhancement kit for the ND front lighting signature.',
    priceRange: { min: 120, max: 150 },
    attributes: { install: 'bolt-on' },
    fitments: [{ vehicleId: '2015-mazda-mx-5-miata-club-20-rwd' }],
  },
  {
    id: 'versatuner-miata-license',
    sku: 'VRS-ND-TUNE',
    name: 'VersaTuner License',
    brand: 'VersaTune',
    category: 'engine',
    keywords: ['engine', 'tune', 'response', 'performance'],
    summary: 'Tuning license for naturally aspirated ND ECU calibration changes.',
    priceRange: { min: 399, max: 449 },
    attributes: { install: 'software', tuneRequired: false },
    fitments: [{ vehicleId: '2015-mazda-mx-5-miata-club-20-rwd' }],
  },
  {
    id: 'verus-miata-rear-spoiler',
    sku: 'VER-ND-SWAN',
    name: 'Rear Ducktail Spoiler',
    brand: 'Verus Engineering',
    category: 'aero',
    keywords: ['aero', 'spoiler', 'style', 'track', 'appearance'],
    summary: 'Small rear ducktail for a more purposeful ND Miata silhouette.',
    priceRange: { min: 389, max: 450 },
    attributes: { install: 'bolt-on', material: 'fiberglass' },
    fitments: [{ vehicleId: '2015-mazda-mx-5-miata-club-20-rwd' }],
  },
  {
    id: 'rotofab-camaro-intake',
    sku: 'RTF-6GEN-SS',
    name: 'Cold Air Intake',
    brand: 'Roto-fab',
    category: 'intake',
    keywords: ['intake', 'sound', 'power', 'response', 'naturally aspirated'],
    summary: 'Well-known intake upgrade for the sixth-gen Camaro SS LT1.',
    priceRange: { min: 465, max: 520 },
    attributes: { install: 'bolt-on', tuneRequired: false },
    fitments: [{ vehicleId: '2017-chevrolet-camaro-ss-coupe-62-rwd' }],
  },
  {
    id: 'mbrp-camaro-axleback',
    sku: 'MBR-6GEN-ABL',
    name: 'Axle-Back Exhaust',
    brand: 'MBRP',
    category: 'exhaust',
    keywords: ['exhaust', 'axle-back', 'sound', 'aggressive', 'v8'],
    summary: 'Straightforward axle-back option for more LT1 sound on a budget.',
    priceRange: { min: 699, max: 760 },
    attributes: { install: 'bolt-on', loudness: 'medium-high' },
    fitments: [{ vehicleId: '2017-chevrolet-camaro-ss-coupe-62-rwd' }],
  },
  {
    id: 'bmr-camaro-lowering-springs',
    sku: 'BMR-6GEN-SPR',
    name: 'Performance Lowering Springs',
    brand: 'BMR',
    category: 'suspension',
    keywords: ['springs', 'lower', 'stance', 'handling', 'street'],
    summary: 'Lowering springs for a more aggressive look and reduced body motion.',
    priceRange: { min: 299, max: 360 },
    attributes: { install: 'moderate', alignmentRequired: true },
    fitments: [{ vehicleId: '2017-chevrolet-camaro-ss-coupe-62-rwd' }],
  },
  {
    id: 'hawk-camaro-track-pads',
    sku: 'HWK-6GEN-DTC',
    name: 'DTC-30 Front Pad Set',
    brand: 'Hawk',
    category: 'brakes',
    keywords: ['brakes', 'pads', 'track', 'stopping'],
    summary: 'Higher-temp front pad set for harder use than a normal street compound.',
    priceRange: { min: 255, max: 305 },
    attributes: { install: 'bolt-on', trackBias: true },
    fitments: [{ vehicleId: '2017-chevrolet-camaro-ss-coupe-62-rwd' }],
  },
  {
    id: 'mrr-camaro-wheel-set',
    sku: 'MRR-M017-20X10-CAM',
    name: 'M017 20-inch Wheel Set',
    brand: 'MRR',
    category: 'wheels',
    keywords: ['wheel', 'wheels', 'stance', 'appearance', 'street'],
    summary: 'Muscle-oriented 20-inch wheel package for a wide, aggressive Camaro look.',
    priceRange: { min: 1840, max: 1990 },
    attributes: { finish: 'gloss black', install: 'bolt-on' },
    fitments: [{ vehicleId: '2017-chevrolet-camaro-ss-coupe-62-rwd' }],
  },
  {
    id: 'diode-camaro-side-markers',
    sku: 'DD-6GEN-SMRK',
    name: 'Smoked LED Side Markers',
    brand: 'Diode Dynamics',
    category: 'lighting',
    keywords: ['lights', 'led', 'lighting', 'appearance'],
    summary: 'Smoked LED side markers for a cleaner sixth-gen Camaro exterior detail.',
    priceRange: { min: 149, max: 179 },
    attributes: { install: 'bolt-on' },
    fitments: [{ vehicleId: '2017-chevrolet-camaro-ss-coupe-62-rwd' }],
  },
  {
    id: 'msd-camaro-lt1-manifold',
    sku: 'MSD-LT1-INT',
    name: 'Atomic AirForce Intake Manifold',
    brand: 'MSD',
    category: 'engine',
    keywords: ['engine', 'power', 'performance', 'response'],
    summary: 'LT1 intake manifold upgrade for naturally aspirated power-focused builds.',
    priceRange: { min: 999, max: 1099 },
    attributes: { install: 'advanced', tuneRequired: true },
    fitments: [{ vehicleId: '2017-chevrolet-camaro-ss-coupe-62-rwd', notes: 'Supporting tune and calibration work recommended' }],
  },
  {
    id: 'zl1addons-camaro-splitter',
    sku: 'ZL1-6GEN-SPL',
    name: 'Front Splitter Extension',
    brand: 'ZL1 Addons',
    category: 'aero',
    keywords: ['aero', 'splitter', 'track', 'appearance'],
    summary: 'Front splitter extension that sharpens the sixth-gen SS front-end look.',
    priceRange: { min: 319, max: 395 },
    attributes: { install: 'bolt-on', material: 'abs' },
    fitments: [{ vehicleId: '2017-chevrolet-camaro-ss-coupe-62-rwd' }],
  },
  {
    id: 'kn-durango-63-intake',
    sku: 'KNN-63-1561',
    name: '63 Series AirCharger Intake',
    brand: 'K&N',
    category: 'intake',
    keywords: ['intake', 'air intake', 'cold air', 'sound', 'response', 'daily', 'suv'],
    summary: 'Open-element intake upgrade commonly offered for the 3.6L Durango platform.',
    priceRange: { min: 399, max: 449 },
    attributes: { install: 'bolt-on', tuneRequired: false },
    fitments: [{ vehicleId: '2014-dodge-durango-limited-36-awd', notes: 'Explicit demo row for the 2014 Durango Limited 3.6L application' }],
  },
  {
    id: 'borla-durango-s-type-catback',
    sku: 'BOR-140626',
    name: 'S-Type Cat-Back Exhaust',
    brand: 'Borla',
    category: 'exhaust',
    keywords: ['exhaust', 'catback', 'sound', 'daily', 'aggressive', 'suv'],
    summary: 'Cat-back exhaust option for owners who want more tone without jumping straight to race-only hardware.',
    priceRange: { min: 1395, max: 1545 },
    attributes: { install: 'moderate', loudness: 'medium' },
    fitments: [{ vehicleId: '2014-dodge-durango-limited-36-awd', notes: 'Use the explicit 3.6L Durango fitment row only; do not generalize across other trims/engines' }],
  },
  {
    id: 'eibach-durango-pro-kit',
    sku: 'EIB-28142.140',
    name: 'Pro-Kit Lowering Springs',
    brand: 'Eibach',
    category: 'suspension',
    keywords: ['springs', 'suspension', 'handling', 'street', 'appearance', 'lower', 'suv'],
    summary: 'Street-oriented spring kit for a lower stance and reduced body motion on the Durango chassis.',
    priceRange: { min: 359, max: 430 },
    attributes: { install: 'moderate', alignmentRequired: true },
    fitments: [{ vehicleId: '2014-dodge-durango-limited-36-awd', notes: 'Demo row is intentionally limited to this exact Durango record' }],
  },
  {
    id: 'powerstop-durango-z23-brakes',
    sku: 'PWR-K7003',
    name: 'Z23 Evolution Sport Brake Kit',
    brand: 'PowerStop',
    category: 'brakes',
    keywords: ['brakes', 'pads', 'rotor', 'stopping', 'daily', 'street', 'family', 'suv'],
    summary: 'Rotor-and-pad package aimed at daily-driven SUV use with a mild performance bias.',
    priceRange: { min: 285, max: 360 },
    attributes: { install: 'moderate', trackBias: false },
    fitments: [{ vehicleId: '2014-dodge-durango-limited-36-awd' }],
  },
  {
    id: 'morimoto-durango-xb-led-fogs',
    sku: 'MRM-LF430',
    name: 'XB LED Fog Light Kit',
    brand: 'Morimoto',
    category: 'lighting',
    keywords: ['lights', 'led', 'lighting', 'appearance', 'daily', 'suv', 'fog lights', 'fog light kit', 'fog lamps'],
    summary: 'LED fog light upgrade that fits the practical daily-driver / OEM+ lane for the Durango.',
    priceRange: { min: 210, max: 260 },
    attributes: { install: 'bolt-on' },
    fitments: [{ vehicleId: '2014-dodge-durango-limited-36-awd', notes: 'Lighting products may vary by factory package; this demo keeps only the explicit Durango row' }],
  },
  ...durangoParts,
]
