import { Part } from './types'

export const partsDatabase: Part[] = [
  // ─── INTAKE ───────────────────────────────────────────────
  {
    id: 'cold-air-intake',
    name: 'Cold Air Intake',
    brand: 'K&N / AEM / Injen',
    category: 'intake',
    subcategory: 'Cold Air Intake',
    description: 'Replaces the restrictive factory airbox with a high-flow intake that pulls cooler, denser air into the engine.',
    longDescription: 'A cold air intake is one of the best bang-for-buck performance modifications available. It replaces the factory air box and filter with a larger diameter intake tube and a high-flow air filter, resulting in improved airflow to the engine. Cooler, denser air means more oxygen for combustion, which translates to more power and improved throttle response.',
    priceRange: { min: 250, max: 450 },
    difficulty: 'bolt-on',
    timeToInstall: '30–60 minutes',
    gainEstimate: '+5–15 hp',
    tags: ['performance', 'weekend-install', 'budget-friendly'],
    focus: ['performance', 'both'],
    budgetTiers: ['under-500', '500-1000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Cold+Air+Intake',
    retailers: [
      {
        name: 'Amazon — Cold Air Intakes',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+cold+air+intake&i=automotive&rh=p_n_feature_keywords_browse-bin%3A7072025011',
        priceNote: 'Verified fitment filters, reviews, fast shipping',
      },
      {
        name: 'K&N Exact Fit Finder',
        icon: '🌐',
        urlTemplate: 'https://www.knfilters.com/find-a-filter?type=filtercharger&year={year}&make={make}&model={model}',
        priceNote: 'K&N\'s tool shows exact kit for your engine code',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search?searchterm={year}+{make}+{model}+cold+air+intake&N=4294940259',
        priceNote: 'Performance retailer with fitment notes',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+cold+air+intake&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings only — compare prices',
      },
    ],
    youtubeQuery: '{year} {make} {model} cold air intake install review',
    benefits: ['Improved throttle response', 'Better engine sound', 'Increased horsepower', 'Improved fuel efficiency at highway speeds'],
    installNotes: 'No tune required. Bolt-on installation. Most kits include all hardware.',
    phase: 1,
  },

  // ─── EXHAUST ──────────────────────────────────────────────
  {
    id: 'catback-exhaust',
    name: 'Cat-Back Exhaust System',
    brand: 'Borla / Magnaflow / Flowmaster',
    category: 'exhaust',
    subcategory: 'Cat-Back System',
    description: 'Full exhaust replacement from the catalytic converter back. Adds aggressive sound and noticeable power gains.',
    longDescription: 'A cat-back exhaust system replaces all exhaust components from the catalytic converter back to the exhaust tips. This includes the mid-pipe, muffler, and tips. A quality cat-back reduces exhaust restriction, adds horsepower, improves torque, and gives your car an aggressive, performance-oriented exhaust note.',
    priceRange: { min: 600, max: 1400 },
    difficulty: 'moderate',
    timeToInstall: '1–3 hours',
    gainEstimate: '+8–20 hp',
    tags: ['performance', 'sound', 'premium'],
    focus: ['performance', 'both'],
    budgetTiers: ['500-1000', '1000-2500'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Cat-Back+Exhaust',
    retailers: [
      {
        name: 'Amazon — Cat-Back Exhaust',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+cat+back+exhaust+system&i=automotive',
        priceNote: 'Top-rated systems with fitment reviews',
      },
      {
        name: 'MagnaFlow Search',
        icon: '🌐',
        urlTemplate: 'https://www.magnaflow.com/search?search={year}+{make}+{model}+exhaust',
        priceNote: 'Brand search for exact MagnaFlow systems',
      },
      {
        name: 'Summit Racing Search',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search/department/exhaust/category/cat-back-exhaust-systems?searchterm={year}+{make}+{model}+cat+back+exhaust',
        priceNote: 'Performance retailer search results',
      },
      {
        name: 'eBay Motors Search',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+catback+exhaust&_sacat=33743',
        priceNote: 'Marketplace search — verify exact fitment before buying',
      },
    ],
    youtubeQuery: '{year} {make} {model} cat back exhaust sound install before after',
    benefits: ['Deep, aggressive exhaust note', 'Improved horsepower & torque', 'Better exhaust flow', 'Stainless steel tips improve appearance'],
    installNotes: 'Professional installation recommended but DIY possible with jack stands and basic tools. May require O2 sensor relocation.',
    phase: 2,
  },

  {
    id: 'performance-headers',
    name: 'Performance Headers',
    brand: 'Hooker / Doug Thorley / JBA',
    category: 'exhaust',
    subcategory: 'Headers',
    description: 'Replaces the factory exhaust manifold with equal-length tubes for maximum exhaust scavenging and horsepower.',
    longDescription: 'Performance headers are one of the biggest single power upgrades you can make on a naturally aspirated engine. They replace the restrictive factory exhaust manifold with equal-length tubes that allow exhaust gases to exit each cylinder without interference from neighboring cylinders.',
    priceRange: { min: 350, max: 800 },
    difficulty: 'advanced',
    timeToInstall: '3–6 hours',
    gainEstimate: '+15–30 hp',
    tags: ['performance', 'must-have'],
    focus: ['performance'],
    budgetTiers: ['500-1000', '1000-2500'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Performance+Headers',
    retailers: [
      {
        name: 'Amazon — Performance Headers',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+performance+headers&i=automotive',
        priceNote: 'Best selection with customer reviews and fitment notes',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search/department/exhaust/category/headers?searchterm={year}+{make}+{model}+headers',
        priceNote: 'Largest headers catalog with tech support',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+headers&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare brands and prices',
      },
      {
        name: 'JBA Headers',
        icon: '⚡',
        urlTemplate: 'https://jbaheaders.com/search?q={make}+{model}',
        priceNote: 'Brand site — vehicle-specific search',
      },
    ],
    youtubeQuery: '{year} {make} {model} headers install dyno results horsepower',
    benefits: ['Significant horsepower gain', 'Improved torque across RPM range', 'Better sound', 'Reduced exhaust gas temperature'],
    installNotes: 'A professional tune is recommended after headers installation to maximize gains. May require catalytic converter relocation.',
    requires: ['catback-exhaust'],
    phase: 3,
  },

  // ─── SUSPENSION ───────────────────────────────────────────
  {
    id: 'coilovers',
    name: 'Coilover Suspension Kit',
    brand: 'BC Racing / KW / Tein',
    category: 'suspension',
    subcategory: 'Coilovers',
    description: 'Fully adjustable height and damping suspension system. Dramatically improves handling and gives your car a perfect stance.',
    longDescription: 'Coilovers are the gold standard suspension upgrade for any performance or stance build. They combine the spring and damper into one adjustable unit, allowing you to fine-tune your ride height, damping stiffness, and sometimes camber. BC Racing coilovers offer excellent quality at a competitive price point.',
    priceRange: { min: 700, max: 1400 },
    difficulty: 'moderate',
    timeToInstall: '3–5 hours',
    gainEstimate: 'Handling: major improvement',
    tags: ['performance', 'style', 'handling', 'premium'],
    focus: ['performance', 'style', 'both'],
    budgetTiers: ['500-1000', '1000-2500'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Coilover+Kit',
    retailers: [
      {
        name: 'Amazon — Coilovers',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+coilover+suspension+kit&i=automotive',
        priceNote: 'Top-rated kits with verified fitment and reviews',
      },
      {
        name: 'BC Racing Direct',
        icon: '⚡',
        urlTemplate: 'https://shop.bcracing-na.com/search?q={year}+{make}+{model}&type=product',
        priceNote: 'Best bang-for-buck coilovers — search your exact car',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+coilovers&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare BC, Tein, KW, Fortune Auto',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search?searchterm={year}+{make}+{model}+coilover+kit',
        priceNote: 'Performance suspension with tech support',
      },
    ],
    youtubeQuery: '{year} {make} {model} coilover install before after stance review',
    benefits: ['Fully adjustable ride height', 'Improved cornering performance', 'Better visual stance', 'Adjustable damping for street or track'],
    installNotes: 'Alignment required after installation. Recommended to use a professional alignment shop. Spring pre-load should be set to your weight.',
    conflictsWith: ['lowering-springs'],
    phase: 2,
  },

  {
    id: 'lowering-springs',
    name: 'Lowering Springs',
    brand: 'Eibach / H&R / Tein',
    category: 'suspension',
    subcategory: 'Springs',
    description: 'Drop your ride height 1–2 inches using your factory shocks. Improves handling and gives a cleaner, more aggressive look.',
    longDescription: 'Lowering springs are a budget-friendly alternative to coilovers. They lower the vehicle\'s center of gravity which improves handling and cornering, and give the car a sportier, more aggressive stance. Eibach Pro-Kit and H&R Sport springs are the most popular choices for a balanced street-performance setup.',
    priceRange: { min: 150, max: 320 },
    difficulty: 'moderate',
    timeToInstall: '2–4 hours',
    gainEstimate: 'Handling: moderate improvement',
    tags: ['style', 'handling', 'budget-friendly', 'weekend-install'],
    focus: ['style', 'both'],
    budgetTiers: ['under-500', '500-1000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Lowering+Springs',
    retailers: [
      {
        name: 'Amazon — Lowering Springs',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+lowering+springs+eibach&i=automotive',
        priceNote: 'Eibach, H&R, and Tein — all fitment-verified with reviews',
      },
      {
        name: 'Eibach Pro-Kit Search',
        icon: '⚡',
        urlTemplate: 'https://eibach.com/search?q={year}+{make}+{model}+pro-kit',
        priceNote: 'Eibach\'s own site — most accurate fitment results',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search?searchterm={year}+{make}+{model}+lowering+springs',
        priceNote: 'Wide selection with tech notes',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+lowering+springs&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings only — compare brands',
      },
    ],
    youtubeQuery: '{year} {make} {model} lowering springs eibach install before after',
    benefits: ['Improved stance and appearance', 'Lower center of gravity', 'Reduced body roll', 'Compatible with factory shocks'],
    installNotes: 'Alignment required after installation. Use spring compressors safely when installing.',
    conflictsWith: ['coilovers'],
    phase: 1,
  },

  {
    id: 'sway-bars',
    name: 'Performance Sway Bars',
    brand: 'Whiteline / Hotchkis / Eibach',
    category: 'suspension',
    subcategory: 'Sway Bars / Anti-Roll Bars',
    description: 'Upgraded front and rear sway bars dramatically reduce body roll and improve corner-entry response.',
    longDescription: 'Sway bars (anti-roll bars) connect the left and right sides of the suspension to reduce body roll during cornering. Upgrading to larger diameter sway bars significantly improves handling response, reduces understeer, and makes the car feel planted and connected in corners.',
    priceRange: { min: 180, max: 400 },
    difficulty: 'moderate',
    timeToInstall: '1–2 hours',
    tags: ['performance', 'handling', 'budget-friendly'],
    focus: ['performance'],
    budgetTiers: ['under-500', '500-1000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Sway+Bars',
    retailers: [
      {
        name: 'Amazon — Sway Bars',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+sway+bar+upgrade&i=automotive',
        priceNote: 'Whiteline, Hotchkis, Eibach — all with fitment reviews',
      },
      {
        name: 'Whiteline Vehicle Search',
        icon: '⚡',
        urlTemplate: 'https://www.whiteline.com.au/vehicleSelectSearch.php?make={make}&model={model}',
        priceNote: 'Best sway bar brand — search your exact model',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search?searchterm={year}+{make}+{model}+sway+bars',
        priceNote: 'Wide selection with tech support',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+sway+bar+anti+roll&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare prices',
      },
    ],
    youtubeQuery: '{year} {make} {model} sway bar install upgrade handling',
    benefits: ['Dramatically reduced body roll', 'Sharper turn-in response', 'Better cornering balance', 'Often includes upgraded end links'],
    phase: 2,
  },

  // ─── BRAKES ───────────────────────────────────────────────
  {
    id: 'performance-brake-pads',
    name: 'Performance Brake Pads',
    brand: 'EBC Yellowstuff / Hawk HPS',
    category: 'brakes',
    subcategory: 'Brake Pads',
    description: 'High-performance brake pads with significantly shorter stopping distances and fade resistance at high temperatures.',
    longDescription: 'EBC Yellowstuff and Hawk HPS performance brake pads are the go-to choice for street/track builds. They offer significantly better stopping power than OEM pads, resist brake fade under hard use, and produce less dust than track-only compounds.',
    priceRange: { min: 80, max: 200 },
    difficulty: 'bolt-on',
    timeToInstall: '45–90 minutes',
    tags: ['performance', 'budget-friendly', 'must-have', 'weekend-install'],
    focus: ['performance', 'both'],
    budgetTiers: ['under-500'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Brake+Pads',
    retailers: [
      {
        name: 'Amazon — Brake Pads',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+performance+brake+pads&i=automotive',
        priceNote: 'EBC, Hawk, PowerStop — all with verified fitment and reviews',
      },
      {
        name: 'EBC Brakes Search',
        icon: '🌐',
        urlTemplate: 'https://www.ebcbrakes.com/products/?s={year}+{make}+{model}+yellowstuff',
        priceNote: 'EBC\'s site — search for your exact Yellowstuff kit',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search?searchterm={year}+{make}+{model}+brake+pads+performance',
        priceNote: 'Wide brake selection with tech notes',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+performance+brake+pads&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare EBC, Hawk, StopTech',
      },
    ],
    youtubeQuery: '{year} {make} {model} performance brake pads install upgrade review',
    benefits: ['Shorter stopping distances', 'Better pedal feel', 'Fade resistant under hard use', 'Works with stock rotors'],
    installNotes: 'Bed in pads properly after installation with 10 progressive stops from 60mph.',
    phase: 1,
  },

  {
    id: 'big-brake-kit',
    name: 'Big Brake Upgrade Kit',
    brand: 'StopTech / Brembo / Wilwood',
    category: 'brakes',
    subcategory: 'Big Brake Kit',
    description: 'Larger rotors with multi-piston calipers for maximum stopping power. Essential for high-horsepower builds.',
    longDescription: 'A big brake kit (BBK) upgrades both the rotors and calipers to larger units, dramatically increasing the brake\'s heat capacity and clamping force. Essential for any build above 400hp or track use. Most kits include slotted/drilled rotors, multi-piston calipers, and stainless steel brake lines.',
    priceRange: { min: 700, max: 2500 },
    difficulty: 'advanced',
    timeToInstall: '3–5 hours',
    tags: ['performance', 'premium', 'must-have'],
    focus: ['performance'],
    budgetTiers: ['1000-2500', '2500-5000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Big+Brake+Kit',
    retailers: [
      {
        name: 'Amazon — Big Brake Kits',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+big+brake+kit+stoptech+brembo&i=automotive',
        priceNote: 'StopTech, Brembo, Wilwood — with fitment notes',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search/department/brakes/category/big-brake-kits?searchterm={year}+{make}+{model}',
        priceNote: 'Largest BBK catalog with vehicle fitment guides',
      },
      {
        name: 'StopTech Brake Systems',
        icon: '⚡',
        urlTemplate: 'https://www.stoptech.com/brake-systems',
        priceNote: 'Premium big brake kits — use their vehicle finder',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+big+brake+kit&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare brands and prices',
      },
    ],
    youtubeQuery: '{year} {make} {model} big brake kit install brembo stoptech review',
    benefits: ['Maximum stopping power', 'Superior heat dissipation', 'Multi-piston calipers for precise modulation', 'Dramatic wheel appearance upgrade'],
    installNotes: 'Wheel fitment check required — many BBKs require 18"+ wheels. Professional installation recommended.',
    phase: 3,
  },

  // ─── WHEELS & TIRES ───────────────────────────────────────
  {
    id: 'aftermarket-wheels',
    name: 'Aftermarket Wheels',
    brand: 'Enkei / Volk / Work / BBS',
    category: 'wheels-tires',
    subcategory: 'Wheels / Rims',
    description: 'Forged or cast performance wheels that are lighter than stock and dramatically transform the car\'s appearance.',
    longDescription: 'Aftermarket wheels are one of the most impactful visual upgrades you can make. Lighter wheels reduce unsprung weight which improves acceleration, braking, and handling. Popular options include the Enkei RPF1 (lightweight budget option), Volk TE37 (premium forged), and BBS RS (classic look).',
    priceRange: { min: 800, max: 2800 },
    difficulty: 'bolt-on',
    timeToInstall: '1 hour (requires tire mount/balance)',
    tags: ['style', 'performance', 'premium'],
    focus: ['style', 'both'],
    budgetTiers: ['500-1000', '1000-2500', '2500-5000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Aftermarket+Wheels',
    retailers: [
      {
        name: 'Amazon — Aftermarket Wheels',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+aftermarket+wheels+rims&i=automotive',
        priceNote: 'Wide selection — filter by bolt pattern and offset',
      },
      {
        name: 'Tire Rack — Wheel Finder',
        icon: '🏁',
        urlTemplate: 'https://www.tirerack.com/wheels/WheelSearchResults.jsp?make={make}&model={model}',
        priceNote: 'Best fitment tools — confirms bolt pattern, offset, center bore',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={make}+{model}+wheels+rims&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — Enkei, Volk, BBS, Work',
      },
      {
        name: 'Discount Tire',
        icon: '🔧',
        urlTemplate: 'https://www.discounttire.com/buy-wheels',
        priceNote: 'Free mount & balance at local stores',
      },
    ],
    youtubeQuery: '{year} {make} {model} aftermarket wheels before after wheel fitment',
    benefits: ['Dramatically improved appearance', 'Reduced unsprung weight', 'Better fitment options', 'Wide variety of styles and finishes'],
    installNotes: 'Verify correct bolt pattern, offset, and center bore before ordering. Tire Rack\'s fitment tool is the best resource.',
    phase: 2,
  },

  {
    id: 'performance-tires',
    name: 'Performance Tires',
    brand: 'Michelin Pilot Sport / Bridgestone Potenza / Continental',
    category: 'wheels-tires',
    subcategory: 'Performance Tires',
    description: 'Ultra-high performance summer tires that unlock the full potential of your suspension and brakes.',
    longDescription: 'Performance tires are the single most impactful handling upgrade available. The Michelin Pilot Sport 4S is widely considered the best all-around UHP tire, offering exceptional dry and wet grip. No suspension or brake upgrade will compensate for poor tire quality.',
    priceRange: { min: 600, max: 1600 },
    difficulty: 'bolt-on',
    timeToInstall: '1 hour (requires mount/balance)',
    tags: ['performance', 'handling', 'must-have'],
    focus: ['performance', 'both'],
    budgetTiers: ['500-1000', '1000-2500'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Performance+Tires',
    retailers: [
      {
        name: 'Amazon — Performance Tires',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k=michelin+pilot+sport+4s+performance+tires&i=automotive',
        priceNote: 'Michelin PS4S, Bridgestone Potenza, Continental ExtremeContact',
      },
      {
        name: 'Tire Rack — Tire Finder',
        icon: '🏁',
        urlTemplate: 'https://www.tirerack.com/tires/TireSearchResults.jsp?make={make}&model={model}',
        priceNote: 'Best tire reviews + fitment guide for your wheel size',
      },
      {
        name: 'Discount Tire',
        icon: '🔧',
        urlTemplate: 'https://www.discounttire.com/buy-tires',
        priceNote: 'Free installation at local stores',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw=michelin+pilot+sport+4s+performance+tires&_sacat=66471&LH_ItemCondition=1000',
        priceNote: 'New tires — compare prices across sizes',
      },
    ],
    youtubeQuery: '{year} {make} {model} performance tires michelin pilot sport review handling test',
    benefits: ['Maximum dry and wet grip', 'Shorter braking distances', 'Improved cornering limits', 'Better steering feel and feedback'],
    installNotes: 'Match tire width and aspect ratio to your wheel size. Check speed rating requirements.',
    phase: 1,
  },

  // ─── EXTERIOR ─────────────────────────────────────────────
  {
    id: 'front-lip-splitter',
    name: 'Front Lip / Splitter',
    brand: 'Roane Concepts / Maxton Design / Carbon Fiber',
    category: 'exterior',
    subcategory: 'Front Lip',
    description: 'Aggressive front lip or splitter that lowers the car\'s front visual profile and adds aerodynamic presence.',
    longDescription: 'A front lip spoiler is one of the cleanest, most affordable exterior mods you can do. It extends the front bumper downward, giving a more aggressive, low look. Polyurethane options are flexible and durable. Carbon fiber options add a premium look but require more care.',
    priceRange: { min: 80, max: 450 },
    difficulty: 'bolt-on',
    timeToInstall: '30–60 minutes',
    tags: ['style', 'budget-friendly', 'weekend-install'],
    focus: ['style', 'both'],
    budgetTiers: ['under-500', '500-1000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Front+Lip',
    retailers: [
      {
        name: 'Amazon',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+front+lip+splitter&i=automotive',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+front+lip+splitter&_sacat=33743',
      },
      {
        name: 'Maxton Design',
        icon: '⚡',
        urlTemplate: 'https://www.maxton-design.com/search?q={make}+{model}',
        priceNote: 'Premium European styling kits',
      },
    ],
    youtubeQuery: '{year} {make} {model} front lip install before after transformation',
    benefits: ['Aggressive front profile', 'Aerodynamic improvement', 'Easy DIY install', 'Available in polyurethane, carbon fiber, or ABS'],
    phase: 1,
  },

  {
    id: 'window-tint',
    name: 'Window Tint',
    brand: '3M Crystalline / Llumar CTX',
    category: 'exterior',
    subcategory: 'Window Tint',
    description: 'Professional-grade window film that blocks UV/heat, improves privacy, and gives the car a sleek, dark appearance.',
    longDescription: '3M Crystalline and Llumar CTX are premium ceramic tint films that block up to 99% of UV rays and significant infrared heat without the dark look of dyed films. A proper tint job transforms the exterior look of any vehicle.',
    priceRange: { min: 200, max: 600 },
    difficulty: 'professional',
    timeToInstall: 'Professional installation (2–4 hours)',
    tags: ['style', 'budget-friendly'],
    focus: ['style', 'both'],
    budgetTiers: ['under-500', '500-1000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Window+Tint',
    retailers: [
      {
        name: 'Amazon — Window Tint Film',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k=3m+crystalline+ceramic+window+tint+film+automotive&i=automotive',
        priceNote: '3M Crystalline, Llumar CTX — professional-grade ceramic film',
      },
      {
        name: 'Find Local Installer',
        icon: '🔧',
        urlTemplate: 'https://www.google.com/search?q=ceramic+window+tint+shop+near+me',
        priceNote: 'Highly recommended — professional install for best results',
      },
      {
        name: '3M Automotive Films',
        icon: '⚡',
        urlTemplate: 'https://www.3m.com/3M/en_US/window-film-us/products/automotive/',
        priceNote: 'Official 3M Crystalline and FX product line',
      },
      {
        name: 'eBay — Tint Film',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw=ceramic+window+tint+film+automotive+{year}+{make}&_sacat=38635&LH_ItemCondition=1000',
        priceNote: 'Pre-cut kits available for many vehicles',
      },
    ],
    youtubeQuery: '{year} {make} {model} window tint before after transformation ceramic',
    benefits: ['UV and heat protection', 'Improved privacy', 'Sleek, uniform exterior look', 'Reduces interior fading'],
    installNotes: 'Check your state\'s legal tint limits before choosing darkness level.',
    phase: 1,
  },

  {
    id: 'rear-spoiler',
    name: 'Rear Spoiler / Wing',
    brand: 'OEM-Style / APR Performance / Carbon Fiber',
    category: 'exterior',
    subcategory: 'Spoiler / Wing',
    description: 'A rear spoiler or wing adds aerodynamic downforce and transforms the rear visual profile of the car.',
    longDescription: 'A rear spoiler or wing is one of the most visually impactful exterior mods. Options range from subtle OEM+ trunk spoilers to aggressive GT-style wings. APR Performance makes some of the best aerodynamically functional wings available.',
    priceRange: { min: 100, max: 800 },
    difficulty: 'moderate',
    timeToInstall: '1–2 hours',
    tags: ['style'],
    focus: ['style', 'both'],
    budgetTiers: ['under-500', '500-1000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Rear+Spoiler',
    retailers: [
      {
        name: 'Amazon — Rear Spoilers',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+rear+spoiler+wing&i=automotive',
        priceNote: 'OEM-style and aggressive GT wings — with fitment reviews',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+rear+spoiler+wing&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare styles and materials',
      },
      {
        name: 'APR Performance',
        icon: '⚡',
        urlTemplate: 'https://www.aprperformance.com/search?q={make}+{model}+wing',
        priceNote: 'Premium aero wings — functional downforce',
      },
      {
        name: 'Maxton Design',
        icon: '🌐',
        urlTemplate: 'https://www.maxton-design.com/search?q={make}+{model}+spoiler',
        priceNote: 'European styling — OEM+ fitment, aggressive looks',
      },
    ],
    youtubeQuery: '{year} {make} {model} spoiler wing install before after exterior',
    benefits: ['Added rear visual aggression', 'Aerodynamic downforce at high speed', 'Wide range of styles and materials', 'Many OEM-style options available painted to match'],
    phase: 2,
  },

  // ─── LIGHTING ─────────────────────────────────────────────
  {
    id: 'led-headlights',
    name: 'LED Headlight Upgrade',
    brand: 'Philips Ultinon / XenonPro / GTR Lighting',
    category: 'lighting',
    subcategory: 'LED Headlights',
    description: 'LED or HID headlight upgrade dramatically improves nighttime visibility and gives a premium, modern look.',
    longDescription: 'LED headlight upgrades replace the standard halogen bulbs with powerful LED units that produce a whiter, brighter light output. They also improve nighttime safety by illuminating more of the road. The Philips Ultinon and GTR Lighting are highly rated plug-and-play options.',
    priceRange: { min: 80, max: 250 },
    difficulty: 'bolt-on',
    timeToInstall: '20–45 minutes',
    tags: ['style', 'budget-friendly', 'weekend-install'],
    focus: ['style', 'both'],
    budgetTiers: ['under-500'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=LED+Headlights',
    retailers: [
      {
        name: 'Amazon — LED Headlights',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+LED+headlight+bulbs+plug+and+play&i=automotive',
        priceNote: 'Philips Ultinon, GTR Lighting, XenonPro — plug-and-play fits',
      },
      {
        name: 'AutoZone',
        icon: '🔧',
        urlTemplate: 'https://www.autozone.com/lighting-and-electrical/headlight-bulb/_/N-kzz2?searchText={year}+{make}+{model}+LED+headlight',
        priceNote: 'Same-day in-store pickup available',
      },
      {
        name: 'GTR Lighting',
        icon: '⚡',
        urlTemplate: 'https://www.gtrlighting.com/search?q={make}+{model}+led+headlight',
        priceNote: 'Enthusiast-grade LEDs — best beam pattern',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+LED+headlight+bulbs&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare brands and brightness ratings',
      },
    ],
    youtubeQuery: '{year} {make} {model} LED headlight upgrade install comparison before after',
    benefits: ['5x brighter than halogen', 'Crisp white light output', 'Plug-and-play fitment', 'Improved nighttime safety'],
    installNotes: 'Check if your car uses projector or reflector housings. Some vehicles may require resistors to prevent flickering.',
    phase: 1,
  },

  // ─── INTERIOR ─────────────────────────────────────────────
  {
    id: 'short-shifter',
    name: 'Short Shifter Kit',
    brand: 'MGW / B&M / Mishimoto',
    category: 'interior',
    subcategory: 'Short Shifter',
    description: 'Reduces throw length and increases shift precision for faster, more connected gear changes.',
    longDescription: 'A short shifter reduces the throw distance required to engage each gear, making shifting faster and more precise. The feel of a quality short shifter transforms the driving experience of any manual transmission car. MGW makes some of the most highly regarded shifters available.',
    priceRange: { min: 150, max: 400 },
    difficulty: 'moderate',
    timeToInstall: '1–2 hours',
    tags: ['performance', 'weekend-install'],
    focus: ['performance', 'both'],
    budgetTiers: ['under-500', '500-1000'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Short+Shifter',
    retailers: [
      {
        name: 'Amazon — Short Shifters',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+short+shifter+kit&i=automotive',
        priceNote: 'MGW, B&M, Mishimoto — all with fitment reviews',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search?searchterm={year}+{make}+{model}+short+shifter',
        priceNote: 'Wide selection with install tech notes',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+short+shifter&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare brands',
      },
      {
        name: 'MGW Race Products',
        icon: '⚡',
        urlTemplate: 'https://www.mgwraceproducts.com/collections/short-shifters',
        priceNote: 'Top-rated short shifters for Mustang, Camaro, and more',
      },
    ],
    youtubeQuery: '{year} {make} {model} short shifter install before after review feel',
    benefits: ['Faster gear changes', 'More precise shift feel', 'Reduced shift throw by 30–50%', 'Improved driving engagement'],
    installNotes: 'Manual transmission only. Some vehicles require center console removal.',
    requiresTransmission: 'manual',
    phase: 2,
  },

  {
    id: 'performance-seats',
    name: 'Performance Racing Seats',
    brand: 'Sparco / Recaro / Bride',
    category: 'interior',
    subcategory: 'Racing Seats',
    description: 'Fixed-back or reclining bucket seats that hold you firmly in place during hard driving and look incredible.',
    longDescription: 'Sparco Sprint and Recaro Sportster are popular choices for street builds that want a performance seat without sacrificing daily comfort. Fixed-back racing seats like the Sparco Circuit provide maximum lateral support but are best for track-focused builds.',
    priceRange: { min: 400, max: 1800 },
    difficulty: 'moderate',
    timeToInstall: '1–3 hours (requires seat brackets)',
    tags: ['style', 'performance', 'premium'],
    focus: ['style', 'performance', 'both'],
    budgetTiers: ['500-1000', '1000-2500'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Racing+Seats',
    retailers: [
      {
        name: 'Amazon — Racing Seats',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k=sparco+recaro+racing+bucket+seat&i=automotive',
        priceNote: 'Sparco, Recaro, Corbeau — top-rated with reviews',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw=sparco+recaro+bucket+racing+seat&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New listings — compare brands and styles',
      },
      {
        name: 'Sparco USA',
        icon: '⚡',
        urlTemplate: 'https://www.sparco-usa.com/collections/seats',
        priceNote: 'Official Sparco — Sprint, Circuit, R100 series',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search/department/interior/category/racing-seats?searchterm={make}+{model}+racing+seat',
        priceNote: 'Recaro, Sparco, Kirkey — with seat bracket pairings',
      },
    ],
    youtubeQuery: '{year} {make} {model} racing seat install sparco recaro review interior',
    benefits: ['Superior lateral support in corners', 'Dramatic interior transformation', 'Lightweight vs stock seats', 'Harness compatible'],
    installNotes: 'Seat brackets specific to your vehicle are required. Check airbag compatibility if removing OEM seats.',
    phase: 3,
  },

  // ─── TUNE ─────────────────────────────────────────────────
  {
    id: 'ecu-tune',
    name: 'ECU Tune / Accessport',
    brand: 'Cobb Tuning / APR / EFI Live',
    category: 'tune',
    subcategory: 'ECU Flash / OBD Tune',
    description: 'Optimizes engine timing, fuel maps, and boost levels in the ECU to safely extract maximum power from your engine.',
    longDescription: 'An ECU tune is the most cost-effective power upgrade available. Cobb\'s Accessport is a popular plug-and-play solution for supported vehicles that allows you to flash pre-made or custom tunes directly to your ECU. A proper tune after intake and exhaust mods can add 20–50hp over stock.',
    priceRange: { min: 500, max: 1500 },
    difficulty: 'bolt-on',
    timeToInstall: '30 minutes (remote tune) or 1 day (dyno tune)',
    gainEstimate: '+20–50 hp (with supporting mods)',
    tags: ['performance', 'must-have', 'premium'],
    focus: ['performance'],
    budgetTiers: ['500-1000', '1000-2500'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=ECU+Tune',
    retailers: [
      {
        name: 'Amazon — Cobb Accessport',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k=cobb+accessport+{make}+{model}+v3&i=automotive',
        priceNote: 'Cobb Accessport V3 — plug-and-play ECU tune for supported vehicles',
      },
      {
        name: 'Cobb Tuning',
        icon: '⚡',
        urlTemplate: 'https://www.cobbtuning.com/pages/vehicle-select',
        priceNote: 'Official Cobb — check if your vehicle is supported',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw=cobb+accessport+{make}+{model}&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New Accessport listings — compare prices',
      },
      {
        name: 'Find Dyno Tuner',
        icon: '🔧',
        urlTemplate: 'https://www.google.com/search?q=dyno+tune+shop+near+me+{make}+{model}',
        priceNote: 'Custom dyno tune — always outperforms off-the-shelf maps',
      },
    ],
    youtubeQuery: '{year} {make} {model} ECU tune dyno horsepower before after results',
    benefits: ['Maximum power from existing mods', 'Improved fuel efficiency', 'Smoother power delivery', 'Removes factory power limiters'],
    installNotes: 'A custom dyno tune will always outperform an off-the-shelf tune. Pair with intake and exhaust for best results.',
    phase: 2,
  },

  // ─── FORCED INDUCTION ─────────────────────────────────────
  {
    id: 'turbo-kit',
    name: 'Turbocharger Kit',
    brand: 'Garrett / Precision / Hellion',
    category: 'forced-induction',
    subcategory: 'Turbo Kit',
    description: 'Full bolt-on turbo kit that forces compressed air into the engine for massive power gains. The ultimate performance upgrade.',
    longDescription: 'A turbocharger kit is the most significant power upgrade available for a naturally aspirated engine. Complete kits include the turbocharger, exhaust manifold, intercooler, boost piping, and wastegate. Power gains of 100–200+ hp are achievable depending on the setup.',
    priceRange: { min: 2000, max: 6000 },
    difficulty: 'professional',
    timeToInstall: '1–3 days professional installation',
    gainEstimate: '+100–250+ hp',
    tags: ['performance', 'premium', 'must-have'],
    focus: ['performance'],
    budgetTiers: ['2500-5000', '5000-10000', '10000+'],
    image: 'https://placehold.co/600x380/111113/9333ea?text=Turbo+Kit',
    retailers: [
      {
        name: 'Amazon — Turbo Kits',
        icon: '🛒',
        urlTemplate: 'https://www.amazon.com/s?k={year}+{make}+{model}+turbo+kit+bolt+on&i=automotive',
        priceNote: 'Complete bolt-on kits — read reviews carefully for your application',
      },
      {
        name: 'Summit Racing',
        icon: '🏁',
        urlTemplate: 'https://www.summitracing.com/search/department/forced-induction?searchterm={year}+{make}+{model}+turbo+kit',
        priceNote: 'Largest forced induction catalog with tech support',
      },
      {
        name: 'eBay Motors',
        icon: '🏷️',
        urlTemplate: 'https://www.ebay.com/sch/i.html?_nkw={year}+{make}+{model}+turbo+kit&_sacat=33743&LH_ItemCondition=1000',
        priceNote: 'New kits — Garrett, Precision, Hellion, and more',
      },
      {
        name: 'Hellion Power Systems',
        icon: '⚡',
        urlTemplate: 'https://www.hellionpowersystems.com/search?q={make}+{model}',
        priceNote: 'Premium twin-turbo kits — industry-leading fitment',
      },
    ],
    youtubeQuery: '{year} {make} {model} turbo kit install build dyno horsepower',
    benefits: ['Massive horsepower gains', 'Completely transforms the car\'s character', 'Scalable power with boost tuning', 'Dramatic sound change under boost'],
    installNotes: 'Requires supporting modifications: fuel injectors, fuel pump, intercooler, and a professional dyno tune. Professional installation strongly recommended.',
    requires: ['ecu-tune'],
    phase: 3,
  },
]
